<?php

function photocrati_theme_register_presets()
{
	PhotocratiTheme_Preset::register(
		'photocrati.preset-fstop',
		'Photocrati F-Stop',
		null,
		PhotocratiTheme_StyleProvider::get(PhotocratiTheme_OptionProviderList::get(
			array(
				'dynamic_style' => 'YES',
				'one_column' => 'OFF',
				'one_column_color' => 'FFFFFF',
				'one_column_logo' => 'OFF',
				'one_column_margin' => '30',
				'display_sidebar' => 'YES',
				'content_width' => '70',
				'sidebar_width' => '30',
				'logo_menu_position' => 'bottom-top',
				'bg_color' => '000000',
				'bg_image' => '',
				'bg_repeat' => 'repeat',
				'header_bg_color' => '000000',
				'header_bg_image' => '',
				'header_bg_repeat' => 'repeat',
				'container_color' => 'transparent',
				'container_border' => '0',
				'container_border_color' => 'FFFFFF',
				'font_color' => 'FFFFFF',
				'font_size' => '12',
				'font_style' => 'Arial, Helvetica, sans-serif',
				'p_line' => '20',
				'p_space' => '10',
				'h1_color' => 'FFFFFF',
				'h1_size' => '22',
				'h1_font_style' => '\'G - Josefin Slab\', serif',
				'h1_font_case' => '',
				'h1_font_weight' => '',
				'h1_font_align' => '',
				'h2_color' => 'FFFFFF',
				'h2_size' => '20',
				'h2_font_style' => '\'G - Josefin Slab\', serif',
				'h2_font_case' => '',
				'h2_font_weight' => '',
				'h3_color' => 'FFFFFF',
				'h3_size' => '18',
				'h3_font_style' => '\'G - Josefin Slab\', serif',
				'h3_font_case' => '',
				'h3_font_weight' => '',
				'h4_color' => 'FFFFFF',
				'h4_size' => '16',
				'h4_font_style' => '\'G - Josefin Slab\', serif',
				'h4_font_case' => '',
				'h4_font_weight' => '',
				'h5_color' => 'FFFFFF',
				'h5_size' => '14',
				'h5_font_style' => '\'G - Josefin Slab\', serif',
				'h5_font_case' => '',
				'h5_font_weight' => '',
				'link_color' => 'eb941a',
				'link_hover_color' => 'ff6600',
				'link_hover_style' => 'none',
				'sidebar_font_color' => 'ababab',
				'sidebar_font_size' => '12',
				'sidebar_font_style' => 'Arial, Helvetica, sans-serif',
				'sidebar_bg_color' => 'transparent',
				'sidebar_link_color' => 'eb941a',
				'sidebar_link_hover_color' => 'ff6600',
				'sidebar_link_hover_style' => 'underline',
				'sidebar_title_color' => 'b0854a',
				'sidebar_title_size' => '14',
				'sidebar_title_style' => 'Arial, Helvetica, sans-serif',
				'menu_style' => 'color',
				'menu_color' => '000000',
				'menu_hover_color' => 'eb941a',
				'menu_font_size' => '12',
				'menu_font_style' => 'Arial, Helvetica, sans-serif',
				'menu_font_color' => 'FFFFFF',
				'menu_font_hover_color' => '704100',
				'menu_font_case' => '',
				'submenu_color' => '474747',
				'submenu_hover_color' => 'eb941a',
				'submenu_font_size' => '12',
				'submenu_font_style' => 'Arial, Helvetica, sans-serif',
				'submenu_font_color' => 'FFFFFF',
				'submenu_font_hover_color' => '704100',
				'submenu_font_case' => '',
				'nextgen_border' => '5',
				'nextgen_border_color' => 'E1E1E1',
				'custom_logo' => 'title',
				'custom_logo_image' => 'Logo_Orange2.png',
				'footer_copy' => '',
				'custom_sidebar' => 'OFF',
				'custom_sidebar_position' => 'ABOVE',
				'custom_sidebar_html' => '',
				'social_media' => 'OFF',
				'social_media_title' => 'Follow Me',
				'social_media_set' => 'small',
				'social_rss' => '',
				'social_email' => '',
				'social_twitter' => '',
				'social_facebook' => '',
				'social_flickr' => '',
				'google_analytics' => '',
				'custom_css' => '#footer {
border-top:0 solid #E8E7E7;
text-align:center;
}',
				'header_height' => '140',
				'header_logo_margin_above' => '60',
				'header_logo_margin_below' => '20',
				'title_size' => '30',
				'title_color' => 'c78425',
				'title_font_style' => '',
				'title_font_weight' => '',
				'title_style' => '\'G - Josefin Slab\', serif',
				'description_size' => '16',
				'description_color' => 'b5b5b5',
				'description_style' => '\'G - Josefin Slab\', serif',
				'bg_top_offset' => '0',
				'container_padding' => '10',
				'footer_font' => '12',
				'footer_font_color' => 'FFFFFF',
				'custom_setting' => '',
				'footer_widget_placement' => '3',
				'footer_background' => '000000',
				'footer_font_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'footer_widget_title' => '16',
				'footer_widget_color' => 'c78425',
				'footer_widget_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'footer_link_color' => 'c78425',
				'footer_link_hover_color' => 'c78425',
				'footer_link_hover_style' => 'none',
				'footer_height' => '250',
				'show_photocrati' => '',
				'page_comments' => 'OFF',
				'blog_meta' => '',		
			),
			'PRESET.preset-fstop'
		))
	);

	PhotocratiTheme_Preset::register(
		'photocrati.preset-emulsion',
		'Photocrati Emulsion',
		null,
		PhotocratiTheme_StyleProvider::get(PhotocratiTheme_OptionProviderList::get(
			array(
				'dynamic_style' => 'YES',
				'one_column' => 'OFF',
				'one_column_color' => 'FFFFFF',
				'one_column_logo' => 'OFF',
				'one_column_margin' => '30',
				'display_sidebar' => 'YES',
				'content_width' => '70',
				'sidebar_width' => '30',
				'logo_menu_position' => 'bottom-top',
				'bg_color' => 'FFFFFF',
				'bg_image' => '',
				'bg_repeat' => 'repeat',
				'header_bg_color' => 'FFFFFF',
				'header_bg_image' => '',
				'header_bg_repeat' => 'repeat',
				'container_color' => 'transparent',
				'container_border' => '0',
				'container_border_color' => '666666',
				'font_color' => '333333',
				'font_size' => '12',
				'font_style' => 'helvetica, arial, sans-serif',
				'p_line' => '20',
				'p_space' => '10',
				'h1_color' => '333333',
				'h1_size' => '22',
				'h1_font_style' => '\'G - Josefin Slab\', serif',
				'h1_font_case' => '',
				'h1_font_weight' => '',
				'h1_font_align' => '',
				'h2_color' => '333333',
				'h2_size' => '20',
				'h2_font_style' => '\'G - Josefin Slab\', serif',
				'h2_font_case' => '',
				'h2_font_weight' => '',
				'h3_color' => '333333',
				'h3_size' => '18',
				'h3_font_style' => '\'G - Josefin Slab\', serif',
				'h3_font_case' => '',
				'h3_font_weight' => '',
				'h4_color' => '333333',
				'h4_size' => '16',
				'h4_font_style' => '\'G - Josefin Slab\', serif',
				'h4_font_case' => '',
				'h4_font_weight' => '',
				'h5_color' => '333333',
				'h5_size' => '14',
				'h5_font_style' => '\'G - Josefin Slab\', serif',
				'h5_font_case' => '',
				'h5_font_weight' => '',
				'link_color' => '5da85b',
				'link_hover_color' => '2ecc29',
				'link_hover_style' => 'none',
				'sidebar_font_color' => '545454',
				'sidebar_font_size' => '12',
				'sidebar_font_style' => 'helvetica, arial, sans-serif',
				'sidebar_bg_color' => 'transparent',
				'sidebar_link_color' => '5da85b',
				'sidebar_link_hover_color' => '2ecc29',
				'sidebar_link_hover_style' => 'none',
				'sidebar_title_color' => 'a6a6a6',
				'sidebar_title_size' => '15',
				'sidebar_title_style' => 'helvetica, arial, sans-serif',
				'menu_style' => 'color',
				'menu_color' => 'FFFFFF',
				'menu_hover_color' => 'E8E8EA',
				'menu_font_size' => '12',
				'menu_font_style' => 'helvetica, arial, sans-serif',
				'menu_font_color' => '666666',
				'menu_font_hover_color' => '5da85b',
				'menu_font_case' => '',
				'submenu_color' => 'E8E8EA',
				'submenu_hover_color' => 'b2d3b1',
				'submenu_font_size' => '12',
				'submenu_font_style' => 'helvetica, arial, sans-serif',
				'submenu_font_color' => '5da85b',
				'submenu_font_hover_color' => '595959',
				'submenu_font_case' => '',
				'nextgen_border' => '1',
				'nextgen_border_color' => 'CCCCCC',
				'custom_logo' => 'title',
				'custom_logo_image' => 'Logo_Tall_Green.png',
				'footer_copy' => '',
				'custom_sidebar' => 'OFF',
				'custom_sidebar_position' => 'ABOVE',
				'custom_sidebar_html' => '',
				'social_media' => 'OFF',
				'social_media_title' => 'Follow Me',
				'social_media_set' => 'small',
				'social_rss' => '',
				'social_email' => '',
				'social_twitter' => '',
				'social_facebook' => '',
				'social_flickr' => '',
				'google_analytics' => '',
				'custom_css' => '#footer {
border-top:0 solid #E8E7E7;
text-align:center;
}

h1 {
border-bottom:0 solid #E1E1E1;
text-align:center;
}',
				'header_height' => '140',
				'header_logo_margin_above' => '60',
				'header_logo_margin_below' => '20',
				'title_size' => '30',
				'title_color' => 'b2d3b1',
				'title_font_style' => '',
				'title_font_weight' => '',
				'title_style' => '\'G - Josefin Slab\', serif',
				'description_size' => '16',
				'description_color' => '999999',
				'description_style' => '\'G - Josefin Slab\', serif',
				'bg_top_offset' => '0',
				'container_padding' => '10',
				'footer_font' => '12',
				'footer_font_color' => '333333',
				'custom_setting' => '',
				'footer_widget_placement' => '3',
				'footer_background' => 'FFFFFF',
				'footer_font_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'footer_widget_title' => '16',
				'footer_widget_color' => 'b2d3b1',
				'footer_widget_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'footer_link_color' => '5da85b',
				'footer_link_hover_color' => 'b2d3b1',
				'footer_link_hover_style' => 'none',
				'footer_height' => '250',
				'show_photocrati' => '',
				'page_comments' => 'OFF',
				'blog_meta' => '',		
			),
			'PRESET.preset-emulsion'
		))
	);

	PhotocratiTheme_Preset::register(
		'photocrati.preset-signature',
		'Photocrati Signature',
		null,
		PhotocratiTheme_StyleProvider::get(PhotocratiTheme_OptionProviderList::get(
			array(
				'dynamic_style' => 'YES',
				'one_column' => 'OFF',
				'one_column_color' => 'FFFFFF',
				'one_column_logo' => 'OFF',
				'one_column_margin' => '30',
				'display_sidebar' => 'YES',
				'content_width' => '70',
				'sidebar_width' => '30',
				'logo_menu_position' => 'bottom-top',
				'bg_color' => '42413F',
				'bg_image' => '',
				'bg_repeat' => 'repeat',
				'header_bg_color' => '42413F',
				'header_bg_image' => '',
				'header_bg_repeat' => 'repeat',
				'container_color' => 'transparent',
				'container_border' => '0',
				'container_border_color' => 'CCCCCC',
				'font_color' => 'F1F1F1',
				'font_size' => '13',
				'font_style' => 'Lucida Grande, Lucida Sans, Lucida Sans Unicode, sans-serif',
				'p_line' => '20',
				'p_space' => '10',
				'h1_color' => 'F0F0EE',
				'h1_size' => '22',
				'h1_font_style' => '\'G - Josefin Slab\', serif',
				'h1_font_case' => '',
				'h1_font_weight' => '',
				'h1_font_align' => '',
				'h2_color' => 'FFFFFF',
				'h2_size' => '20',
				'h2_font_style' => '\'G - Josefin Slab\', serif',
				'h2_font_case' => '',
				'h2_font_weight' => '',
				'h3_color' => 'FFFFFF',
				'h3_size' => '18',
				'h3_font_style' => '\'G - Josefin Slab\', serif',
				'h3_font_case' => '',
				'h3_font_weight' => '',
				'h4_color' => 'FFFFFF',
				'h4_size' => '16',
				'h4_font_style' => '\'G - Josefin Slab\', serif',
				'h4_font_case' => '',
				'h4_font_weight' => '',
				'h5_color' => 'FFFFFF',
				'h5_size' => '14',
				'h5_font_style' => '\'G - Josefin Slab\', serif',
				'h5_font_case' => '',
				'h5_font_weight' => '',
				'link_color' => '6197CA',
				'link_hover_color' => '1c84e6',
				'link_hover_style' => 'none',
				'sidebar_font_color' => 'a8a8a8',
				'sidebar_font_size' => '12',
				'sidebar_font_style' => 'Lucida Grande, Lucida Sans, Lucida Sans Unicode, sans-serif',
				'sidebar_bg_color' => 'transparent',
				'sidebar_link_color' => '6197CA',
				'sidebar_link_hover_color' => '3597f2',
				'sidebar_link_hover_style' => 'underline',
				'sidebar_title_color' => 'bcd4eb',
				'sidebar_title_size' => '16',
				'sidebar_title_style' => 'Lucida Grande, Lucida Sans, Lucida Sans Unicode, sans-serif',
				'menu_style' => 'color',
				'menu_color' => '42413F',
				'menu_hover_color' => '666666',
				'menu_font_size' => '12',
				'menu_font_style' => 'Lucida Grande, Lucida Sans, Lucida Sans Unicode, sans-serif',
				'menu_font_color' => 'ffffff',
				'menu_font_hover_color' => 'bcd4eb',
				'menu_font_case' => '',
				'submenu_color' => 'C2C2C2',
				'submenu_hover_color' => 'A0A6AA',
				'submenu_font_size' => '12',
				'submenu_font_style' => 'Lucida Grande, Lucida Sans, Lucida Sans Unicode, sans-serif',
				'submenu_font_color' => '1B1B1B',
				'submenu_font_hover_color' => 'F0F0EE',
				'submenu_font_case' => '',
				'nextgen_border' => '5',
				'nextgen_border_color' => 'E1E1E1',
				'custom_logo' => 'title',
				'custom_logo_image' => 'Logo_Script_Blue.png',
				'footer_copy' => '',
				'custom_sidebar' => 'OFF',
				'custom_sidebar_position' => 'ABOVE',
				'custom_sidebar_html' => '',
				'social_media' => 'OFF',
				'social_media_title' => 'Follow Me',
				'social_media_set' => 'small',
				'social_rss' => '',
				'social_email' => '',
				'social_twitter' => '',
				'social_facebook' => '',
				'social_flickr' => '',
				'google_analytics' => '',
				'custom_css' => '#footer {
border-top:0;
text-align:center;
}

h1 {
border-bottom:0px;
}

p {
margin-bottom:0.5em;
}',
				'header_height' => '140',
				'header_logo_margin_above' => '60',
				'header_logo_margin_below' => '20',
				'title_size' => '30',
				'title_color' => 'bcd4eb',
				'title_font_style' => '',
				'title_font_weight' => '',
				'title_style' => '\'G - Josefin Slab\', serif',
				'description_size' => '16',
				'description_color' => 'CCCCCC',
				'description_style' => '\'G - Josefin Slab\', serif',
				'bg_top_offset' => '0',
				'container_padding' => '10',
				'footer_font' => '12',
				'footer_font_color' => 'FFFFFF',
				'custom_setting' => '',
				'footer_widget_placement' => '3',
				'footer_background' => '42413F',
				'footer_font_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'footer_widget_title' => '16',
				'footer_widget_color' => 'bcd4eb',
				'footer_widget_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'footer_link_color' => '6197CA',
				'footer_link_hover_color' => 'bcd4eb',
				'footer_link_hover_style' => 'none',
				'footer_height' => '250',
				'show_photocrati' => '',
				'page_comments' => 'OFF',
				'blog_meta' => '',		
			),
			'PRESET.preset-signature'
		))
	);

	PhotocratiTheme_Preset::register(
		'photocrati.preset-vignette',
		'Photocrati Vignette',
		null,
		PhotocratiTheme_StyleProvider::get(PhotocratiTheme_OptionProviderList::get(
			array(
				'dynamic_style' => 'YES',
				'one_column' => 'OFF',
				'one_column_color' => 'FFFFFF',
				'one_column_logo' => 'OFF',
				'one_column_margin' => '30',
				'display_sidebar' => 'YES',
				'content_width' => '73',
				'sidebar_width' => '27',
				'logo_menu_position' => 'right-left',
				'bg_color' => '067506',
				'bg_image' => 'Green_BG.jpg',
				'bg_repeat' => 'no-repeat',
				'header_bg_color' => '000000',
				'header_bg_image' => '',
				'header_bg_repeat' => 'repeat',
				'container_color' => 'e1e8d0',
				'container_border' => '0',
				'container_border_color' => 'd9f5a2',
				'font_color' => '000000',
				'font_size' => '13',
				'font_style' => 'Lucida Grande, Lucida Sans, Lucida Sans Unicode, sans-serif',
				'p_line' => '20',
				'p_space' => '10',
				'h1_color' => '4a640b',
				'h1_size' => '26',
				'h1_font_style' => '\'G - Josefin Slab\', serif',
				'h1_font_case' => '',
				'h1_font_weight' => '',
				'h1_font_align' => '',
				'h2_color' => '4a640b',
				'h2_size' => '24',
				'h2_font_style' => '\'G - Josefin Slab\', serif',
				'h2_font_case' => '',
				'h2_font_weight' => '',
				'h3_color' => '4a640b',
				'h3_size' => '22',
				'h3_font_style' => '\'G - Josefin Slab\', serif',
				'h3_font_case' => '',
				'h3_font_weight' => '',
				'h4_color' => '4a640b',
				'h4_size' => '20',
				'h4_font_style' => '\'G - Josefin Slab\', serif',
				'h4_font_case' => '',
				'h4_font_weight' => '',
				'h5_color' => '4a640b',
				'h5_size' => '18',
				'h5_font_style' => '\'G - Josefin Slab\', serif',
				'h5_font_case' => '',
				'h5_font_weight' => '',
				'link_color' => '6ea34b',
				'link_hover_color' => '8bc714',
				'link_hover_style' => 'underline',
				'sidebar_font_color' => '5c5c5c',
				'sidebar_font_size' => '12',
				'sidebar_font_style' => 'Lucida Grande, Lucida Sans, Lucida Sans Unicode, sans-serif',
				'sidebar_bg_color' => 'transparent',
				'sidebar_link_color' => '417e4a',
				'sidebar_link_hover_color' => '417e4a',
				'sidebar_link_hover_style' => 'underline',
				'sidebar_title_color' => '417e4a',
				'sidebar_title_size' => '14',
				'sidebar_title_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'menu_style' => 'color',
				'menu_color' => '000000',
				'menu_hover_color' => '067506',
				'menu_font_size' => '13',
				'menu_font_style' => 'Lucida Grande, Lucida Sans, Lucida Sans Unicode, sans-serif',
				'menu_font_color' => 'ffffff',
				'menu_font_hover_color' => 'fefeb9',
				'menu_font_case' => '',
				'submenu_color' => '000000',
				'submenu_hover_color' => '067506',
				'submenu_font_size' => '12',
				'submenu_font_style' => 'Lucida Grande, Lucida Sans, Lucida Sans Unicode, sans-serif',
				'submenu_font_color' => 'FFFFFF',
				'submenu_font_hover_color' => 'fefeb9',
				'submenu_font_case' => '',
				'nextgen_border' => '5',
				'nextgen_border_color' => '007401',
				'custom_logo' => 'title',
				'custom_logo_image' => 'Logo_Shiny_Green.png',
				'footer_copy' => '',
				'custom_sidebar' => 'OFF',
				'custom_sidebar_position' => 'ABOVE',
				'custom_sidebar_html' => '',
				'social_media' => 'OFF',
				'social_media_title' => 'Follow Me',
				'social_media_set' => 'small',
				'social_rss' => '',
				'social_email' => '',
				'social_twitter' => '',
				'social_facebook' => '',
				'social_flickr' => '',
				'google_analytics' => '',
				'custom_css' => '.menu ul {
line-height:2;
}

.menu a:link, .menu a:visited {
padding:93px 17px 47px;
}

h1 {
border-bottom:0px;
}

h2 {
font-family:Georgia, Times, Sans Serif;
}

div.sidebar {
padding: 20px;
}

div.slideshow {
margin-bottom:20px;
}

p {
margin-bottom:0.5em;
line-height:1.9em;
}',
				'header_height' => '120',
				'header_logo_margin_above' => '15',
				'header_logo_margin_below' => '10',
				'title_size' => '30',
				'title_color' => 'e6e6a1',
				'title_font_style' => '',
				'title_font_weight' => '',
				'title_style' => '\'G - Josefin Slab\', serif',
				'description_size' => '16',
				'description_color' => 'b5b5b5',
				'description_style' => '\'G - Josefin Slab\', serif',
				'bg_top_offset' => '0',
				'container_padding' => '30',
				'footer_font' => '12',
				'footer_font_color' => 'FFFFFF',
				'custom_setting' => '',
				'footer_widget_placement' => '3',
				'footer_background' => '000000',
				'footer_font_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'footer_widget_title' => '16',
				'footer_widget_color' => 'e6e6a1',
				'footer_widget_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'footer_link_color' => 'e6e6a1',
				'footer_link_hover_color' => 'e6e6a1',
				'footer_link_hover_style' => 'none',
				'footer_height' => '250',
				'show_photocrati' => '',
				'page_comments' => 'OFF',
				'blog_meta' => '',		
			),
			'PRESET.preset-vignette'
		))
	);

	PhotocratiTheme_Preset::register(
		'photocrati.preset-canvas',
		'Photocrati Canvas',
		null,
		PhotocratiTheme_StyleProvider::get(PhotocratiTheme_OptionProviderList::get(
			array(
				'dynamic_style' => 'YES',
				'one_column' => 'OFF',
				'one_column_color' => 'FFFFFF',
				'one_column_logo' => 'OFF',
				'one_column_margin' => '30',
				'display_sidebar' => 'N0',
				'content_width' => '100',
				'sidebar_width' => '30',
				'logo_menu_position' => 'bottom-top',
				'bg_color' => 'FFFFFF',
				'bg_image' => 'Muslin_BG.jpg',
				'bg_repeat' => 'repeat',
				'header_bg_color' => 'FFFFFF',
				'header_bg_image' => '',
				'header_bg_repeat' => 'repeat',
				'container_color' => 'FFFFFF',
				'container_border' => '0',
				'container_border_color' => '666666',
				'font_color' => '333333',
				'font_size' => '14',
				'font_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'p_line' => '20',
				'p_space' => '10',
				'h1_color' => '944C7D',
				'h1_size' => '22',
				'h1_font_style' => '\'G - Josefin Slab\', serif',
				'h1_font_case' => '',
				'h1_font_weight' => '',
				'h1_font_align' => '',
				'h2_color' => '944C7D',
				'h2_size' => '20',
				'h2_font_style' => '\'G - Josefin Slab\', serif',
				'h2_font_case' => '',
				'h2_font_weight' => '',
				'h3_color' => '944C7D',
				'h3_size' => '18',
				'h3_font_style' => '\'G - Josefin Slab\', serif',
				'h3_font_case' => '',
				'h3_font_weight' => '',
				'h4_color' => '944C7D',
				'h4_size' => '16',
				'h4_font_style' => '\'G - Josefin Slab\', serif',
				'h4_font_case' => '',
				'h4_font_weight' => '',
				'h5_color' => '944C7D',
				'h5_size' => '14',
				'h5_font_style' => '\'G - Josefin Slab\', serif',
				'h5_font_case' => '',
				'h5_font_weight' => '',
				'link_color' => 'e65370',
				'link_hover_color' => 'c2adbd',
				'link_hover_style' => 'none',
				'sidebar_font_color' => '333333',
				'sidebar_font_size' => '12',
				'sidebar_font_style' => 'Arial, Helvetica, sans-serif',
				'sidebar_bg_color' => 'transparent',
				'sidebar_link_color' => '0072CB',
				'sidebar_link_hover_color' => 'c2adbd',
				'sidebar_link_hover_style' => 'underline',
				'sidebar_title_color' => '333333',
				'sidebar_title_size' => '14',
				'sidebar_title_style' => 'Arial, Helvetica, sans-serif',
				'menu_style' => 'color',
				'menu_color' => 'FFFFFF',
				'menu_hover_color' => 'e3d6c6',
				'menu_font_size' => '12',
				'menu_font_style' => 'helvetica, arial, sans-serif',
				'menu_font_color' => '995083',
				'menu_font_hover_color' => 'e55070',
				'menu_font_case' => '',
				'submenu_color' => 'f5efe7',
				'submenu_hover_color' => 'e3d6c6',
				'submenu_font_size' => '12',
				'submenu_font_style' => 'helvetica, arial, sans-serif',
				'submenu_font_color' => '73604a',
				'submenu_font_hover_color' => 'e55070',
				'submenu_font_case' => '',
				'nextgen_border' => '0',
				'nextgen_border_color' => 'ffffff',
				'custom_logo' => 'title',
				'custom_logo_image' => 'Logo_Fade_Pink.png',
				'footer_copy' => '',
				'custom_sidebar' => 'OFF',
				'custom_sidebar_position' => 'ABOVE',
				'custom_sidebar_html' => '',
				'social_media' => 'OFF',
				'social_media_title' => 'Follow Me',
				'social_media_set' => 'small',
				'social_rss' => '',
				'social_email' => '',
				'social_twitter' => '',
				'social_facebook' => '',
				'social_flickr' => '',
				'google_analytics' => '',
				'custom_css' => '.widget-title, .widgettitle {
       margin-top:5px;
}

.widget-title, .widgettitle {
color:#944C7D;
font-family:Georgia,Times,Serif;
font-size:17px;
font-weight:bold;
margin-bottom:21px;
}

p {
margin-bottom:2.5em;
}

.widget-title, .widgettitle {
padding:4px 0;
}

div.slideshow {
margin-bottom: 23px;
}',
				'header_height' => '160',
				'header_logo_margin_above' => '60',
				'header_logo_margin_below' => '20',
				'title_size' => '30',
				'title_color' => 'c2adbd',
				'title_font_style' => '',
				'title_font_weight' => '',
				'title_style' => '\'G - Josefin Slab\', serif',
				'description_size' => '16',
				'description_color' => '999999',
				'description_style' => '\'G - Josefin Slab\', serif',
				'bg_top_offset' => '0',
				'container_padding' => '30',
				'footer_font' => '12',
				'footer_font_color' => '333333',
				'custom_setting' => '',
				'footer_widget_placement' => '3',
				'footer_background' => 'FFFFFF',
				'footer_font_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'footer_widget_title' => '16',
				'footer_widget_color' => 'c2adbd',
				'footer_widget_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'footer_link_color' => 'e55070',
				'footer_link_hover_color' => 'c2adbd',
				'footer_link_hover_style' => 'none',
				'footer_height' => '250',
				'show_photocrati' => '',
				'page_comments' => 'OFF',
				'blog_meta' => '',		
			),
			'PRESET.preset-canvas'
		))
	);

	PhotocratiTheme_Preset::register(
		'photocrati.preset-lightbox',
		'Photocrati Lightbox',
		null,
		PhotocratiTheme_StyleProvider::get(PhotocratiTheme_OptionProviderList::get(
			array(
				'dynamic_style' => 'YES',
				'one_column' => 'OFF',
				'one_column_color' => 'FFFFFF',
				'one_column_logo' => 'OFF',
				'one_column_margin' => '30',
				'display_sidebar' => 'YES',
				'content_width' => '70',
				'sidebar_width' => '30',
				'logo_menu_position' => 'left-right',
				'bg_color' => 'FFFFFF',
				'bg_image' => '',
				'bg_repeat' => 'repeat',
				'header_bg_color' => 'FFFFFF',
				'header_bg_image' => '',
				'header_bg_repeat' => 'repeat',
				'container_color' => 'transparent',
				'container_border' => '0',
				'container_border_color' => 'CCCCCC',
				'font_color' => '666666',
				'font_size' => '13',
				'font_style' => 'helvetica, arial, sans-serif',
				'p_line' => '20',
				'p_space' => '10',
				'h1_color' => '7695B2',
				'h1_size' => '22',
				'h1_font_style' => '\'G - Josefin Slab\', serif',
				'h1_font_case' => '',
				'h1_font_weight' => '',
				'h1_font_align' => '',
				'h2_color' => '333333',
				'h2_size' => '20',
				'h2_font_style' => '\'G - Josefin Slab\', serif',
				'h2_font_case' => '',
				'h2_font_weight' => '',
				'h3_color' => '333333',
				'h3_size' => '18',
				'h3_font_style' => '\'G - Josefin Slab\', serif',
				'h3_font_case' => '',
				'h3_font_weight' => '',
				'h4_color' => '333333',
				'h4_size' => '16',
				'h4_font_style' => '\'G - Josefin Slab\', serif',
				'h4_font_case' => '',
				'h4_font_weight' => '',
				'h5_color' => '333333',
				'h5_size' => '14',
				'h5_font_style' => '\'G - Josefin Slab\', serif',
				'h5_font_case' => '',
				'h5_font_weight' => '',
				'link_color' => '2B5780',
				'link_hover_color' => '266ead',
				'link_hover_style' => 'underline',
				'sidebar_font_color' => '666666',
				'sidebar_font_size' => '12',
				'sidebar_font_style' => 'Verdana, Arial, Helvetica, sans-serif',
				'sidebar_bg_color' => 'transparent',
				'sidebar_link_color' => '2B5780',
				'sidebar_link_hover_color' => '2B5780',
				'sidebar_link_hover_style' => 'underline',
				'sidebar_title_color' => '333333',
				'sidebar_title_size' => '14',
				'sidebar_title_style' => 'Arial, Helvetica, sans-serif',
				'menu_style' => 'transparent',
				'menu_color' => 'FFFFFF',
				'menu_hover_color' => 'FFFFFF',
				'menu_font_size' => '12',
				'menu_font_style' => 'Arial, Helvetica, sans-serif',
				'menu_font_color' => 'A8A8A8',
				'menu_font_hover_color' => '2D73B6',
				'menu_font_case' => '',
				'submenu_color' => 'E8E8E8',
				'submenu_hover_color' => 'C8C9CB',
				'submenu_font_size' => '12',
				'submenu_font_style' => 'Arial, Helvetica, sans-serif',
				'submenu_font_color' => '484848',
				'submenu_font_hover_color' => '2D73B6',
				'submenu_font_case' => '',
				'nextgen_border' => '5',
				'nextgen_border_color' => 'CCCCCC',
				'custom_logo' => 'title',
				'custom_logo_image' => 'Logo_Steel.png',
				'footer_copy' => '',
				'custom_sidebar' => 'OFF',
				'custom_sidebar_position' => 'ABOVE',
				'custom_sidebar_html' => '',
				'social_media' => 'OFF',
				'social_media_title' => 'Follow Me',
				'social_media_set' => 'small',
				'social_rss' => '',
				'social_email' => '',
				'social_twitter' => '',
				'social_facebook' => '',
				'social_flickr' => '',
				'google_analytics' => '',
				'custom_css' => 'p {
margin-bottom:0.5em;
}

#footer {
border-top:0 solid #E8E7E7;
text-align:center;
}',
				'header_height' => '120',
				'header_logo_margin_above' => '25',
				'header_logo_margin_below' => '10',
				'title_size' => '30',
				'title_color' => '7695b2',
				'title_font_style' => '',
				'title_font_weight' => '',
				'title_style' => '\'G - Josefin Slab\', serif',
				'description_size' => '16',
				'description_color' => '999999',
				'description_style' => '\'G - Josefin Slab\', serif',
				'bg_top_offset' => '0',
				'container_padding' => '10',
				'footer_font' => '12',
				'footer_font_color' => '333333',
				'custom_setting' => '',
				'footer_widget_placement' => '3',
				'footer_background' => 'FFFFFF',
				'footer_font_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'footer_widget_title' => '16',
				'footer_widget_color' => '7695b2',
				'footer_widget_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'footer_link_color' => '7695b2',
				'footer_link_hover_color' => '7695b2',
				'footer_link_hover_style' => 'none',
				'footer_height' => '250',
				'show_photocrati' => '',
				'page_comments' => 'OFF',
				'blog_meta' => '',		
			),
			'PRESET.preset-lightbox'
		))
	);

	PhotocratiTheme_Preset::register(
		'photocrati.preset-darkroom',
		'Photocrati Darkroom',
		null,
		PhotocratiTheme_StyleProvider::get(PhotocratiTheme_OptionProviderList::get(
			array(
				'dynamic_style' => 'YES',
				'one_column' => 'OFF',
				'one_column_color' => 'FFFFFF',
				'one_column_logo' => 'OFF',
				'one_column_margin' => '30',
				'display_sidebar' => 'YES',
				'content_width' => '70',
				'sidebar_width' => '30',
				'logo_menu_position' => 'left-right',
				'bg_color' => '000000',
				'bg_image' => '',
				'bg_repeat' => 'repeat',
				'header_bg_color' => '000000',
				'header_bg_image' => '',
				'header_bg_repeat' => 'repeat',
				'container_color' => 'transparent',
				'container_border' => '0',
				'container_border_color' => 'CCCCCC',
				'font_color' => 'F1F1F1',
				'font_size' => '13',
				'font_style' => 'helvetica, arial, sans-serif',
				'p_line' => '20',
				'p_space' => '10',
				'h1_color' => 'F0F0EE',
				'h1_size' => '22',
				'h1_font_style' => '\'G - Josefin Slab\', serif',
				'h1_font_case' => '',
				'h1_font_weight' => '',
				'h1_font_align' => '',
				'h2_color' => 'FFFFFF',
				'h2_size' => '20',
				'h2_font_style' => '\'G - Josefin Slab\', serif',
				'h2_font_case' => '',
				'h2_font_weight' => '',
				'h3_color' => 'FFFFFF',
				'h3_size' => '18',
				'h3_font_style' => '\'G - Josefin Slab\', serif',
				'h3_font_case' => '',
				'h3_font_weight' => '',
				'h4_color' => 'FFFFFF',
				'h4_size' => '16',
				'h4_font_style' => '\'G - Josefin Slab\', serif',
				'h4_font_case' => '',
				'h4_font_weight' => '',
				'h5_color' => 'FFFFFF',
				'h5_size' => '14',
				'h5_font_style' => '\'G - Josefin Slab\', serif',
				'h5_font_case' => '',
				'h5_font_weight' => '',
				'link_color' => '7c943b',
				'link_hover_color' => 'a9e600',
				'link_hover_style' => 'underline',
				'sidebar_font_color' => 'F1F1F1',
				'sidebar_font_size' => '12',
				'sidebar_font_style' => 'Verdana, Arial, Helvetica, sans-serif',
				'sidebar_bg_color' => 'transparent',
				'sidebar_link_color' => '6197CA',
				'sidebar_link_hover_color' => '6197CA',
				'sidebar_link_hover_style' => 'underline',
				'sidebar_title_color' => 'FFFFFF',
				'sidebar_title_size' => '14',
				'sidebar_title_style' => 'Arial, Helvetica, sans-serif',
				'menu_style' => 'transparent',
				'menu_color' => '000000',
				'menu_hover_color' => '000000',
				'menu_font_size' => '12',
				'menu_font_style' => 'helvetica, arial, sans-serif',
				'menu_font_color' => 'c2c2c2',
				'menu_font_hover_color' => '9ac22b',
				'menu_font_case' => '',
				'submenu_color' => 'bdbdbd',
				'submenu_hover_color' => '1F1F1F',
				'submenu_font_size' => '12',
				'submenu_font_style' => 'helvetica, arial, sans-serif',
				'submenu_font_color' => '35382d',
				'submenu_font_hover_color' => '9ac22b',
				'submenu_font_case' => '',
				'nextgen_border' => '5',
				'nextgen_border_color' => 'E1E1E1',
				'custom_logo' => 'title',
				'custom_logo_image' => 'Logo_Stretch_Green.png',
				'footer_copy' => '',
				'custom_sidebar' => 'OFF',
				'custom_sidebar_position' => 'ABOVE',
				'custom_sidebar_html' => '',
				'social_media' => 'OFF',
				'social_media_title' => 'Follow Me',
				'social_media_set' => 'small',
				'social_rss' => '',
				'social_email' => '',
				'social_twitter' => '',
				'social_facebook' => '',
				'social_flickr' => '',
				'google_analytics' => '',
				'custom_css' => 'p {
margin-bottom:0.5em;
}

h1 {
border-bottom:0px;
}

#footer {
border-top:0px;
}',
				'header_height' => '120',
				'header_logo_margin_above' => '15',
				'header_logo_margin_below' => '10',
				'title_size' => '30',
				'title_color' => '8ca644',
				'title_font_style' => '',
				'title_font_weight' => '',
				'title_style' => '\'G - Josefin Slab\', serif',
				'description_size' => '16',
				'description_color' => 'b5b5b5',
				'description_style' => '\'G - Josefin Slab\', serif',
				'bg_top_offset' => '0',
				'container_padding' => '10',
				'footer_font' => '12',
				'footer_font_color' => 'F1F1F1',
				'custom_setting' => '',
				'footer_widget_placement' => '3',
				'footer_background' => '000000',
				'footer_font_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'footer_widget_title' => '16',
				'footer_widget_color' => '8ca644',
				'footer_widget_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'footer_link_color' => '8ca644',
				'footer_link_hover_color' => '8ca644',
				'footer_link_hover_style' => 'none',
				'footer_height' => '250',
				'show_photocrati' => '',
				'page_comments' => 'OFF',
				'blog_meta' => '',		
			),
			'PRESET.preset-darkroom'
		))
	);

	PhotocratiTheme_Preset::register(
		'photocrati.preset-exposure',
		'Photocrati Exposure',
		null,
		PhotocratiTheme_StyleProvider::get(PhotocratiTheme_OptionProviderList::get(
			array(
				'dynamic_style' => 'YES',
				'one_column' => 'OFF',
				'one_column_color' => 'FFFFFF',
				'one_column_logo' => 'OFF',
				'one_column_margin' => '30',
				'display_sidebar' => 'YES',
				'content_width' => '70',
				'sidebar_width' => '30',
				'logo_menu_position' => 'left-right',
				'bg_color' => '24221f',
				'bg_image' => '',
				'bg_repeat' => 'repeat',
				'header_bg_color' => '24221f',
				'header_bg_image' => '',
				'header_bg_repeat' => 'repeat',
				'container_color' => 'transparent',
				'container_border' => '0',
				'container_border_color' => 'CCCCCC',
				'font_color' => 'F1F1F1',
				'font_size' => '13',
				'font_style' => 'Tahoma, Trebuchet, Helvetica, sans-serif',
				'p_line' => '20',
				'p_space' => '10',
				'h1_color' => 'F0F0EE',
				'h1_size' => '22',
				'h1_font_style' => '\'G - Josefin Slab\', serif',
				'h1_font_case' => '',
				'h1_font_weight' => '',
				'h1_font_align' => '',
				'h2_color' => 'FFFFFF',
				'h2_size' => '20',
				'h2_font_style' => '\'G - Josefin Slab\', serif',
				'h2_font_case' => '',
				'h2_font_weight' => '',
				'h3_color' => 'FFFFFF',
				'h3_size' => '18',
				'h3_font_style' => '\'G - Josefin Slab\', serif',
				'h3_font_case' => '',
				'h3_font_weight' => '',
				'h4_color' => 'FFFFFF',
				'h4_size' => '16',
				'h4_font_style' => '\'G - Josefin Slab\', serif',
				'h4_font_case' => '',
				'h4_font_weight' => '',
				'h5_color' => 'FFFFFF',
				'h5_size' => '14',
				'h5_font_style' => '\'G - Josefin Slab\', serif',
				'h5_font_case' => '',
				'h5_font_weight' => '',
				'link_color' => '6197CA',
				'link_hover_color' => '2993f5',
				'link_hover_style' => 'underline',
				'sidebar_font_color' => 'c2c2c2',
				'sidebar_font_size' => '12',
				'sidebar_font_style' => 'Tahoma, Trebuchet, Helvetica, sans-serif',
				'sidebar_bg_color' => 'transparent',
				'sidebar_link_color' => '6197CA',
				'sidebar_link_hover_color' => '2c92f2',
				'sidebar_link_hover_style' => 'underline',
				'sidebar_title_color' => 'FFFFFF',
				'sidebar_title_size' => '14',
				'sidebar_title_style' => 'Tahoma, Trebuchet, Helvetica, sans-serif',
				'menu_style' => 'transparent',
				'menu_color' => '42413F',
				'menu_hover_color' => '42413F',
				'menu_font_size' => '12',
				'menu_font_style' => 'Tahoma, Trebuchet, Helvetica, sans-serif',
				'menu_font_color' => '8C8C8C',
				'menu_font_hover_color' => '2f90eb',
				'menu_font_case' => '',
				'submenu_color' => '999999',
				'submenu_hover_color' => '2f90eb',
				'submenu_font_size' => '12',
				'submenu_font_style' => 'Tahoma, Trebuchet, Helvetica, sans-serif',
				'submenu_font_color' => '1B1B1B',
				'submenu_font_hover_color' => 'F0F0EE',
				'submenu_font_case' => '',
				'nextgen_border' => '5',
				'nextgen_border_color' => 'E1E1E1',
				'custom_logo' => 'title',
				'custom_logo_image' => 'Logo_Bright_Blue.png',
				'footer_copy' => '',
				'custom_sidebar' => 'OFF',
				'custom_sidebar_position' => 'ABOVE',
				'custom_sidebar_html' => '',
				'social_media' => 'OFF',
				'social_media_title' => 'Follow Me',
				'social_media_set' => 'small',
				'social_rss' => '',
				'social_email' => '',
				'social_twitter' => '',
				'social_facebook' => '',
				'social_flickr' => '',
				'google_analytics' => '',
				'custom_css' => '#footer {
border-top:0 solid #E8E7E7;
text-align:center;
}

h1 {
border-bottom:0 solid #E1E1E1;
}',
				'header_height' => '120',
				'header_logo_margin_above' => '15',
				'header_logo_margin_below' => '10',
				'title_size' => '30',
				'title_color' => '637a8f',
				'title_font_style' => '',
				'title_font_weight' => '',
				'title_style' => '\'G - Josefin Slab\', serif',
				'description_size' => '16',
				'description_color' => 'b5b5b5',
				'description_style' => '\'G - Josefin Slab\', serif',
				'bg_top_offset' => '0',
				'container_padding' => '10',
				'footer_font' => '12',
				'footer_font_color' => 'F1F1F1',
				'custom_setting' => '',
				'footer_widget_placement' => '3',
				'footer_background' => '24221f',
				'footer_font_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'footer_widget_title' => '16',
				'footer_widget_color' => '637a8f',
				'footer_widget_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'footer_link_color' => '637a8f',
				'footer_link_hover_color' => '637a8f',
				'footer_link_hover_style' => 'none',
				'footer_height' => '250',
				'show_photocrati' => '',
				'page_comments' => 'OFF',
				'blog_meta' => '',		
			),
			'PRESET.preset-exposure'
		))
	);

	PhotocratiTheme_Preset::register(
		'photocrati.preset-rangefinder',
		'Photocrati Rangefinder',
		null,
		PhotocratiTheme_StyleProvider::get(PhotocratiTheme_OptionProviderList::get(
			array(
				'dynamic_style' => 'YES',
				'one_column' => 'OFF',
				'one_column_color' => 'FFFFFF',
				'one_column_logo' => 'OFF',
				'one_column_margin' => '30',
				'display_sidebar' => 'YES',
				'content_width' => '70',
				'sidebar_width' => '30',
				'logo_menu_position' => 'top-bottom',
				'bg_color' => '2f1c0b',
				'bg_image' => 'Wood_BG.jpg',
				'bg_repeat' => 'repeat-x',
				'header_bg_color' => 'ebe8dd',
				'header_bg_image' => '',
				'header_bg_repeat' => 'repeat',
				'container_color' => 'transparent',
				'container_border' => '0',
				'container_border_color' => 'CCCCCC',
				'font_color' => 'ebe8dd',
				'font_size' => '13',
				'font_style' => 'helvetica, arial, sans-serif',
				'p_line' => '20',
				'p_space' => '10',
				'h1_color' => 'ffffff',
				'h1_size' => '24',
				'h1_font_style' => '\'G - Josefin Slab\', serif',
				'h1_font_case' => '',
				'h1_font_weight' => '',
				'h1_font_align' => '',
				'h2_color' => 'd4c6a3',
				'h2_size' => '20',
				'h2_font_style' => '\'G - Josefin Slab\', serif',
				'h2_font_case' => '',
				'h2_font_weight' => '',
				'h3_color' => 'ded7ca',
				'h3_size' => '18',
				'h3_font_style' => '\'G - Josefin Slab\', serif',
				'h3_font_case' => '',
				'h3_font_weight' => '',
				'h4_color' => 'c5b383',
				'h4_size' => '16',
				'h4_font_style' => '\'G - Josefin Slab\', serif',
				'h4_font_case' => '',
				'h4_font_weight' => '',
				'h5_color' => 'c5b383',
				'h5_size' => '14',
				'h5_font_style' => '\'G - Josefin Slab\', serif',
				'h5_font_case' => '',
				'h5_font_weight' => '',
				'link_color' => 'be3501',
				'link_hover_color' => 'eb551e',
				'link_hover_style' => 'none',
				'sidebar_font_color' => 'c5b383',
				'sidebar_font_size' => '12',
				'sidebar_font_style' => 'helvetica, arial, sans-serif',
				'sidebar_bg_color' => 'transparent',
				'sidebar_link_color' => 'be3501',
				'sidebar_link_hover_color' => 'eb551e',
				'sidebar_link_hover_style' => 'underline',
				'sidebar_title_color' => 'FFFFFF',
				'sidebar_title_size' => '16',
				'sidebar_title_style' => 'helvetica, arial, sans-serif',
				'menu_style' => 'transparent',
				'menu_color' => 'FFFFFF',
				'menu_hover_color' => 'FFFFFF',
				'menu_font_size' => '14',
				'menu_font_style' => 'helvetica, arial, sans-serif',
				'menu_font_color' => '280b03',
				'menu_font_hover_color' => 'be3501',
				'menu_font_case' => '',
				'submenu_color' => 'f5f3eb',
				'submenu_hover_color' => 'ccc4a7',
				'submenu_font_size' => '12',
				'submenu_font_style' => 'helvetica, arial, sans-serif',
				'submenu_font_color' => '280b03',
				'submenu_font_hover_color' => 'be3501',
				'submenu_font_case' => '',
				'nextgen_border' => '1',
				'nextgen_border_color' => 'f5f3ed',
				'custom_logo' => 'title',
				'custom_logo_image' => 'Logo_Brown.png',
				'footer_copy' => '',
				'custom_sidebar' => 'OFF',
				'custom_sidebar_position' => 'ABOVE',
				'custom_sidebar_html' => '',
				'social_media' => 'OFF',
				'social_media_title' => 'Follow Me',
				'social_media_set' => 'small',
				'social_rss' => '',
				'social_email' => '',
				'social_twitter' => '',
				'social_facebook' => '',
				'social_flickr' => '',
				'google_analytics' => '',
				'custom_css' => 'h1 {
     border-bottom: 0px;
     padding-top: 24px;

}

h2 {
     padding-top: 41px;
}

#menu_wrapper {
     margin-top: -7px;
}

.widget-title, .widgettitle {
     padding-top: 12px;
]

#footer {
     border-top: 0px;
}',
				'header_height' => '140',
				'header_logo_margin_above' => '5',
				'header_logo_margin_below' => '20',
				'title_size' => '30',
				'title_color' => 'ad9966',
				'title_font_style' => '',
				'title_font_weight' => '',
				'title_style' => '\'G - Josefin Slab\', serif',
				'description_size' => '16',
				'description_color' => '666666',
				'description_style' => '\'G - Josefin Slab\', serif',
				'bg_top_offset' => '0',
				'container_padding' => '10',
				'footer_font' => '12',
				'footer_font_color' => '333333',
				'custom_setting' => '',
				'footer_widget_placement' => '3',
				'footer_background' => 'ebe8dd',
				'footer_font_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'footer_widget_title' => '16',
				'footer_widget_color' => 'ad9966',
				'footer_widget_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'footer_link_color' => 'be3501',
				'footer_link_hover_color' => 'ad9966',
				'footer_link_hover_style' => 'none',
				'footer_height' => '250',
				'show_photocrati' => '',
				'page_comments' => 'OFF',
				'blog_meta' => '',		
			),
			'PRESET.preset-rangefinder'
		))
	);

	PhotocratiTheme_Preset::register(
		'photocrati.preset-polarized',
		'Photocrati Polarized',
		null,
		PhotocratiTheme_StyleProvider::get(PhotocratiTheme_OptionProviderList::get(
			array(
				'dynamic_style' => 'YES',
				'one_column' => 'OFF',
				'one_column_color' => 'FFFFFF',
				'one_column_logo' => 'OFF',
				'one_column_margin' => '30',
				'display_sidebar' => 'YES',
				'content_width' => '70',
				'sidebar_width' => '30',
				'logo_menu_position' => 'left-right',
				'bg_color' => '000000',
				'bg_image' => 'Grille_BG.jpg',
				'bg_repeat' => 'repeat-x',
				'header_bg_color' => 'ffffff',
				'header_bg_image' => '',
				'header_bg_repeat' => 'repeat',
				'container_color' => 'e3e3e3',
				'container_border' => '9',
				'container_border_color' => 'fffcf7',
				'font_color' => '423f3d',
				'font_size' => '11',
				'font_style' => 'Lucida Grande, Lucida Sans, Lucida Sans Unicode, sans-serif',
				'p_line' => '20',
				'p_space' => '10',
				'h1_color' => '274a6b',
				'h1_size' => '20',
				'h1_font_style' => '\'G - Josefin Slab\', serif',
				'h1_font_case' => '',
				'h1_font_weight' => '',
				'h1_font_align' => '',
				'h2_color' => '274a6b',
				'h2_size' => '18',
				'h2_font_style' => '\'G - Josefin Slab\', serif',
				'h2_font_case' => '',
				'h2_font_weight' => '',
				'h3_color' => '274a6b',
				'h3_size' => '16',
				'h3_font_style' => '\'G - Josefin Slab\', serif',
				'h3_font_case' => '',
				'h3_font_weight' => '',
				'h4_color' => '274a6b',
				'h4_size' => '14',
				'h4_font_style' => '\'G - Josefin Slab\', serif',
				'h4_font_case' => '',
				'h4_font_weight' => '',
				'h5_color' => '274a6b',
				'h5_size' => '12',
				'h5_font_style' => '\'G - Josefin Slab\', serif',
				'h5_font_case' => '',
				'h5_font_weight' => '',
				'link_color' => '6197CA',
				'link_hover_color' => '61b3ff',
				'link_hover_style' => 'none',
				'sidebar_font_color' => '383738',
				'sidebar_font_size' => '12',
				'sidebar_font_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'sidebar_bg_color' => 'transparent',
				'sidebar_link_color' => '6197CA',
				'sidebar_link_hover_color' => '61b3ff',
				'sidebar_link_hover_style' => 'underline',
				'sidebar_title_color' => '274a6b',
				'sidebar_title_size' => '14',
				'sidebar_title_style' => 'Lucida Grande, Lucida Sans, Lucida Sans Unicode, sans-serif',
				'menu_style' => 'transparent',
				'menu_color' => '42413F',
				'menu_hover_color' => '42413F',
				'menu_font_size' => '11',
				'menu_font_style' => 'Lucida Grande, Lucida Sans, Lucida Sans Unicode, sans-serif',
				'menu_font_color' => '8C8C8C',
				'menu_font_hover_color' => '6197ca',
				'menu_font_case' => '',
				'submenu_color' => '6f7378',
				'submenu_hover_color' => '6197ca',
				'submenu_font_size' => '11',
				'submenu_font_style' => 'Lucida Grande, Lucida Sans, Lucida Sans Unicode, sans-serif',
				'submenu_font_color' => '1B1B1B',
				'submenu_font_hover_color' => 'ffffff',
				'submenu_font_case' => '',
				'nextgen_border' => '5',
				'nextgen_border_color' => 'E1E1E1',
				'custom_logo' => 'title',
				'custom_logo_image' => 'Logo_Steel.png',
				'footer_copy' => '',
				'custom_sidebar' => 'OFF',
				'custom_sidebar_position' => 'ABOVE',
				'custom_sidebar_html' => '',
				'social_media' => 'OFF',
				'social_media_title' => 'Follow Me',
				'social_media_set' => 'small',
				'social_rss' => '',
				'social_email' => '',
				'social_twitter' => '',
				'social_facebook' => '',
				'social_flickr' => '',
				'google_analytics' => '',
				'custom_css' => '.menu ul {
       line-height: 1.5em;
}

p {
margin-bottom:0.5em;
}',
				'header_height' => '140',
				'header_logo_margin_above' => '15',
				'header_logo_margin_below' => '10',
				'title_size' => '30',
				'title_color' => '57697a',
				'title_font_style' => '',
				'title_font_weight' => '',
				'title_style' => '\'G - Josefin Slab\', serif',
				'description_size' => '16',
				'description_color' => '999999',
				'description_style' => '\'G - Josefin Slab\', serif',
				'bg_top_offset' => '20',
				'container_padding' => '20',
				'footer_font' => '12',
				'footer_font_color' => '333333',
				'custom_setting' => '',
				'footer_widget_placement' => '3',
				'footer_background' => 'FFFFFF',
				'footer_font_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'footer_widget_title' => '16',
				'footer_widget_color' => '57697a',
				'footer_widget_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'footer_link_color' => '57697a',
				'footer_link_hover_color' => '57697a',
				'footer_link_hover_style' => 'none',
				'footer_height' => '250',
				'show_photocrati' => '',
				'page_comments' => 'OFF',
				'blog_meta' => '',		
			),
			'PRESET.preset-polarized'
		))
	);

	PhotocratiTheme_Preset::register(
		'photocrati.preset-wideangle',
		'Photocrati Wide Angle',
		null,
		PhotocratiTheme_StyleProvider::get(PhotocratiTheme_OptionProviderList::get(
			array(
				'dynamic_style' => 'YES',
				'one_column' => 'OFF',
				'one_column_color' => 'FFFFFF',
				'one_column_logo' => 'OFF',
				'one_column_margin' => '30',
				'display_sidebar' => 'YES',
				'content_width' => '70',
				'sidebar_width' => '30',
				'logo_menu_position' => 'left-right',
				'bg_color' => '000000',
				'bg_image' => '',
				'bg_repeat' => 'repeat',
				'header_bg_color' => 'ffffff',
				'header_bg_image' => 'header-bg.jpg',
				'header_bg_repeat' => 'repeat-x',
				'container_color' => 'transparent',
				'container_border' => '0',
				'container_border_color' => 'CCCCCC',
				'font_color' => 'E1E1E1',
				'font_size' => '13',
				'font_style' => 'helvetica, arial, sans-serif',
				'p_line' => '20',
				'p_space' => '10',
				'h1_color' => 'f09f8f',
				'h1_size' => '22',
				'h1_font_style' => '\'G - Josefin Slab\', serif',
				'h1_font_case' => '',
				'h1_font_weight' => '',
				'h1_font_align' => '',
				'h2_color' => 'FFFFFF',
				'h2_size' => '20',
				'h2_font_style' => '\'G - Josefin Slab\', serif',
				'h2_font_case' => '',
				'h2_font_weight' => '',
				'h3_color' => 'FFFFFF',
				'h3_size' => '18',
				'h3_font_style' => '\'G - Josefin Slab\', serif',
				'h3_font_case' => '',
				'h3_font_weight' => '',
				'h4_color' => 'FFFFFF',
				'h4_size' => '16',
				'h4_font_style' => '\'G - Josefin Slab\', serif',
				'h4_font_case' => '',
				'h4_font_weight' => '',
				'h5_color' => 'FFFFFF',
				'h5_size' => '14',
				'h5_font_style' => '\'G - Josefin Slab\', serif',
				'h5_font_case' => '',
				'h5_font_weight' => '',
				'link_color' => '995c53',
				'link_hover_color' => 'd46b58',
				'link_hover_style' => 'none',
				'sidebar_font_color' => 'E1E1E1',
				'sidebar_font_size' => '12',
				'sidebar_font_style' => 'helvetica, arial, sans-serif',
				'sidebar_bg_color' => 'transparent',
				'sidebar_link_color' => 'f09f8f',
				'sidebar_link_hover_color' => 'd46b58',
				'sidebar_link_hover_style' => 'none',
				'sidebar_title_color' => 'a8a8a8',
				'sidebar_title_size' => '16',
				'sidebar_title_style' => 'helvetica, arial, sans-serif',
				'menu_style' => 'transparent',
				'menu_color' => 'FFFFFF',
				'menu_hover_color' => 'FFFFFF',
				'menu_font_size' => '12',
				'menu_font_style' => 'helvetica, arial, sans-serif',
				'menu_font_color' => 'd4d4d4',
				'menu_font_hover_color' => 'd46b58',
				'menu_font_case' => '',
				'submenu_color' => 'E8E8E8',
				'submenu_hover_color' => 'd46b58',
				'submenu_font_size' => '12',
				'submenu_font_style' => 'helvetica, arial, sans-serif',
				'submenu_font_color' => '995c53',
				'submenu_font_hover_color' => 'ffffff',
				'submenu_font_case' => '',
				'nextgen_border' => '5',
				'nextgen_border_color' => 'E1E1E1',
				'custom_logo' => 'title',
				'custom_logo_image' => 'Logo_Melon.png',
				'footer_copy' => '',
				'custom_sidebar' => 'OFF',
				'custom_sidebar_position' => 'ABOVE',
				'custom_sidebar_html' => '',
				'social_media' => 'OFF',
				'social_media_title' => 'Follow Me',
				'social_media_set' => 'small',
				'social_rss' => '',
				'social_email' => '',
				'social_twitter' => '',
				'social_facebook' => '',
				'social_flickr' => '',
				'google_analytics' => '',
				'custom_css' => '#footer {
border-top:0;
text-align:center;
}

h1 {
border-bottom:0px;
}

p {
margin-bottom:0.5em;
line-height:1.7em;
}',
				'header_height' => '120',
				'header_logo_margin_above' => '11',
				'header_logo_margin_below' => '10',
				'title_size' => '30',
				'title_color' => 'd46b58',
				'title_font_style' => '',
				'title_font_weight' => '',
				'title_style' => '\'G - Josefin Slab\', serif',
				'description_size' => '16',
				'description_color' => '999999',
				'description_style' => '\'G - Josefin Slab\', serif',
				'bg_top_offset' => '0',
				'container_padding' => '20',
				'footer_font' => '12',
				'footer_font_color' => '333333',
				'custom_setting' => '',
				'footer_widget_placement' => '3',
				'footer_background' => 'FFFFFF',
				'footer_font_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'footer_widget_title' => '16',
				'footer_widget_color' => 'd46b58',
				'footer_widget_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'footer_link_color' => 'd46b58',
				'footer_link_hover_color' => 'd46b58',
				'footer_link_hover_style' => 'none',
				'footer_height' => '250',
				'show_photocrati' => '',
				'page_comments' => 'OFF',
				'blog_meta' => '',		
			),
			'PRESET.preset-wideangle'
		))
	);

	PhotocratiTheme_Preset::register(
		'photocrati.preset-silverhalide',
		'Photocrati Silver Halide',
		null,
		PhotocratiTheme_StyleProvider::get(PhotocratiTheme_OptionProviderList::get(
			array(
				'dynamic_style' => 'YES',
				'one_column' => 'OFF',
				'one_column_color' => 'FFFFFF',
				'one_column_logo' => 'OFF',
				'one_column_margin' => '30',
				'display_sidebar' => 'YES',
				'content_width' => '70',
				'sidebar_width' => '30',
				'logo_menu_position' => 'left-right',
				'bg_color' => 'FFFFFF',
				'bg_image' => '',
				'bg_repeat' => 'repeat',
				'header_bg_color' => '000000',
				'header_bg_image' => 'header-bg-blk.jpg',
				'header_bg_repeat' => 'repeat-x',
				'container_color' => 'transparent',
				'container_border' => '0',
				'container_border_color' => 'CCCCCC',
				'font_color' => '333333',
				'font_size' => '12',
				'font_style' => 'Lucida Grande, Lucida Sans, Lucida Sans Unicode, sans-serif',
				'p_line' => '20',
				'p_space' => '10',
				'h1_color' => '786644',
				'h1_size' => '22',
				'h1_font_style' => '\'G - Josefin Slab\', serif',
				'h1_font_case' => '',
				'h1_font_weight' => '',
				'h1_font_align' => '',
				'h2_color' => '333333',
				'h2_size' => '20',
				'h2_font_style' => '\'G - Josefin Slab\', serif',
				'h2_font_case' => '',
				'h2_font_weight' => '',
				'h3_color' => '333333',
				'h3_size' => '18',
				'h3_font_style' => '\'G - Josefin Slab\', serif',
				'h3_font_case' => '',
				'h3_font_weight' => '',
				'h4_color' => '333333',
				'h4_size' => '16',
				'h4_font_style' => '\'G - Josefin Slab\', serif',
				'h4_font_case' => '',
				'h4_font_weight' => '',
				'h5_color' => '333333',
				'h5_size' => '14',
				'h5_font_style' => '\'G - Josefin Slab\', serif',
				'h5_font_case' => '',
				'h5_font_weight' => '',
				'link_color' => 'cbb07b',
				'link_hover_color' => 'e3cc9e',
				'link_hover_style' => 'none',
				'sidebar_font_color' => '757375',
				'sidebar_font_size' => '12',
				'sidebar_font_style' => 'Lucida Grande, Lucida Sans, Lucida Sans Unicode, sans-serif',
				'sidebar_bg_color' => 'transparent',
				'sidebar_link_color' => 'b39968',
				'sidebar_link_hover_color' => 'f0d198',
				'sidebar_link_hover_style' => 'none',
				'sidebar_title_color' => '786644',
				'sidebar_title_size' => '14',
				'sidebar_title_style' => 'Lucida Grande, Lucida Sans, Lucida Sans Unicode, sans-serif',
				'menu_style' => 'transparent',
				'menu_color' => '000000',
				'menu_hover_color' => '000000',
				'menu_font_size' => '12',
				'menu_font_style' => 'Lucida Grande, Lucida Sans, Lucida Sans Unicode, sans-serif',
				'menu_font_color' => 'c9ac71',
				'menu_font_hover_color' => 'd4d0d4',
				'menu_font_case' => '',
				'submenu_color' => '333333',
				'submenu_hover_color' => '666666',
				'submenu_font_size' => '12',
				'submenu_font_style' => 'Lucida Grande, Lucida Sans, Lucida Sans Unicode, sans-serif',
				'submenu_font_color' => 'cbb07b',
				'submenu_font_hover_color' => 'e3cc9e',
				'submenu_font_case' => '',
				'nextgen_border' => '5',
				'nextgen_border_color' => 'CCCCCC',
				'custom_logo' => 'title',
				'custom_logo_image' => 'Logo_Gold.png',
				'footer_copy' => '',
				'custom_sidebar' => 'OFF',
				'custom_sidebar_position' => 'ABOVE',
				'custom_sidebar_html' => '',
				'social_media' => 'OFF',
				'social_media_title' => 'Follow Me',
				'social_media_set' => 'small',
				'social_rss' => '',
				'social_email' => '',
				'social_twitter' => '',
				'social_facebook' => '',
				'social_flickr' => '',
				'google_analytics' => '',
				'custom_css' => '#footer {
border-top:0;
text-align:center;
}

h1 {
border-bottom:0px;
}

p {
margin-bottom:0.5em;
line-height:1.7em;
}',
				'header_height' => '120',
				'header_logo_margin_above' => '11',
				'header_logo_margin_below' => '10',
				'title_size' => '30',
				'title_color' => 'c9ac71',
				'title_font_style' => '',
				'title_font_weight' => '',
				'title_style' => '\'G - Josefin Slab\', serif',
				'description_size' => '16',
				'description_color' => 'b5b5b5',
				'description_style' => '\'G - Josefin Slab\', serif',
				'bg_top_offset' => '0',
				'container_padding' => '20',
				'footer_font' => '12',
				'footer_font_color' => 'F1F1F1',
				'custom_setting' => '',
				'footer_widget_placement' => '3',
				'footer_background' => '000000',
				'footer_font_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'footer_widget_title' => '16',
				'footer_widget_color' => 'c9ac71',
				'footer_widget_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'footer_link_color' => 'c9ac71',
				'footer_link_hover_color' => 'c9ac71',
				'footer_link_hover_style' => 'none',
				'footer_height' => '250',
				'show_photocrati' => '',
				'page_comments' => 'OFF',
				'blog_meta' => '',		
			),
			'PRESET.preset-silverhalide'
		))
	);

	PhotocratiTheme_Preset::register(
		'photocrati.preset-filter',
		'Photocrati Filter',
		null,
		PhotocratiTheme_StyleProvider::get(PhotocratiTheme_OptionProviderList::get(
			array(
				'dynamic_style' => 'YES',
				'one_column' => 'OFF',
				'one_column_color' => 'FFFFFF',
				'one_column_logo' => 'OFF',
				'one_column_margin' => '30',
				'display_sidebar' => 'YES',
				'content_width' => '70',
				'sidebar_width' => '30',
				'logo_menu_position' => 'left-right',
				'bg_color' => 'a5a6a1',
				'bg_image' => '',
				'bg_repeat' => 'repeat',
				'header_bg_color' => '2E2E2E',
				'header_bg_image' => '',
				'header_bg_repeat' => 'repeat-x',
				'container_color' => 'transparent',
				'container_border' => '0',
				'container_border_color' => 'CCCCCC',
				'font_color' => '000000',
				'font_size' => '12',
				'font_style' => 'Lucida Grande, Lucida Sans, Lucida Sans Unicode, sans-serif',
				'p_line' => '20',
				'p_space' => '10',
				'h1_color' => '565945',
				'h1_size' => '22',
				'h1_font_style' => '\'G - Josefin Slab\', serif',
				'h1_font_case' => '',
				'h1_font_weight' => '',
				'h1_font_align' => '',
				'h2_color' => '737851',
				'h2_size' => '20',
				'h2_font_style' => '\'G - Josefin Slab\', serif',
				'h2_font_case' => '',
				'h2_font_weight' => '',
				'h3_color' => '000000',
				'h3_size' => '18',
				'h3_font_style' => '\'G - Josefin Slab\', serif',
				'h3_font_case' => '',
				'h3_font_weight' => '',
				'h4_color' => '000000',
				'h4_size' => '16',
				'h4_font_style' => '\'G - Josefin Slab\', serif',
				'h4_font_case' => '',
				'h4_font_weight' => '',
				'h5_color' => '000000',
				'h5_size' => '14',
				'h5_font_style' => '\'G - Josefin Slab\', serif',
				'h5_font_case' => '',
				'h5_font_weight' => '',
				'link_color' => '91995e',
				'link_hover_color' => '94a683',
				'link_hover_style' => 'none',
				'sidebar_font_color' => '424242',
				'sidebar_font_size' => '12',
				'sidebar_font_style' => 'Lucida Grande, Lucida Sans, Lucida Sans Unicode, sans-serif',
				'sidebar_bg_color' => 'transparent',
				'sidebar_link_color' => '91995e',
				'sidebar_link_hover_color' => '94a683',
				'sidebar_link_hover_style' => 'none',
				'sidebar_title_color' => 'f1ffe3',
				'sidebar_title_size' => '16',
				'sidebar_title_style' => 'Lucida Grande, Lucida Sans, Lucida Sans Unicode, sans-serif',
				'menu_style' => 'transparent',
				'menu_color' => '2E2E2E',
				'menu_hover_color' => '2E2E2E',
				'menu_font_size' => '12',
				'menu_font_style' => 'Arial, Helvetica, sans-serif',
				'menu_font_color' => 'faffe3',
				'menu_font_hover_color' => 'd4f52e',
				'menu_font_case' => '',
				'submenu_color' => '999999',
				'submenu_hover_color' => 'C8C9CB',
				'submenu_font_size' => '12',
				'submenu_font_style' => 'Arial, Helvetica, sans-serif',
				'submenu_font_color' => 'FFFFFF',
				'submenu_font_hover_color' => '333333',
				'submenu_font_case' => '',
				'nextgen_border' => '5',
				'nextgen_border_color' => 'E1E1E1',
				'custom_logo' => 'title',
				'custom_logo_image' => 'Logo_Lime.png',
				'footer_copy' => '',
				'custom_sidebar' => 'OFF',
				'custom_sidebar_position' => 'ABOVE',
				'custom_sidebar_html' => '',
				'social_media' => 'OFF',
				'social_media_title' => 'Follow Me',
				'social_media_set' => 'small',
				'social_rss' => '',
				'social_email' => '',
				'social_twitter' => '',
				'social_facebook' => '',
				'social_flickr' => '',
				'google_analytics' => '',
				'custom_css' => '#footer {
border-top:0;
text-align:right;
}

h1 {
border-bottom:0px;
}

p {
margin-bottom:0.5em;
line-height:1.7em;
}',
				'header_height' => '120',
				'header_logo_margin_above' => '15',
				'header_logo_margin_below' => '10',
				'title_size' => '30',
				'title_color' => '91995e',
				'title_font_style' => '',
				'title_font_weight' => '',
				'title_style' => '\'G - Josefin Slab\', serif',
				'description_size' => '16',
				'description_color' => 'CCCCCC',
				'description_style' => '\'G - Josefin Slab\', serif',
				'bg_top_offset' => '0',
				'container_padding' => '20',
				'footer_font' => '12',
				'footer_font_color' => 'FFFFFF',
				'custom_setting' => '',
				'footer_widget_placement' => '3',
				'footer_background' => '2E2E2E',
				'footer_font_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'footer_widget_title' => '16',
				'footer_widget_color' => '91995e',
				'footer_widget_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'footer_link_color' => '91995e',
				'footer_link_hover_color' => '91995e',
				'footer_link_hover_style' => 'none',
				'footer_height' => '250',
				'show_photocrati' => '',
				'page_comments' => 'OFF',
				'blog_meta' => '',		
			),
			'PRESET.preset-filter'
		))
	);

	PhotocratiTheme_Preset::register(
		'photocrati.preset-bokeh',
		'Photocrati Bokeh',
		null,
		PhotocratiTheme_StyleProvider::get(PhotocratiTheme_OptionProviderList::get(
			array(
				'dynamic_style' => 'YES',
				'one_column' => 'OFF',
				'one_column_color' => 'FFFFFF',
				'one_column_logo' => 'OFF',
				'one_column_margin' => '30',
				'display_sidebar' => 'YES',
				'content_width' => '70',
				'sidebar_width' => '30',
				'logo_menu_position' => 'left-right',
				'bg_color' => '000000',
				'bg_image' => 'background_bokeh.jpg',
				'bg_repeat' => 'repeat-x',
				'header_bg_color' => 'FFFFFF',
				'header_bg_image' => 'polnlig_header_bg.gif',
				'header_bg_repeat' => 'repeat-x',
				'container_color' => 'transparent',
				'container_border' => '0',
				'container_border_color' => 'CCCCCC',
				'font_color' => 'E1E1E1',
				'font_size' => '12',
				'font_style' => 'Arial, Helvetica, sans-serif',
				'p_line' => '20',
				'p_space' => '10',
				'h1_color' => 'f04a16',
				'h1_size' => '22',
				'h1_font_style' => '\'G - Josefin Slab\', serif',
				'h1_font_case' => '',
				'h1_font_weight' => '',
				'h1_font_align' => '',
				'h2_color' => 'FFFFFF',
				'h2_size' => '20',
				'h2_font_style' => '\'G - Josefin Slab\', serif',
				'h2_font_case' => '',
				'h2_font_weight' => '',
				'h3_color' => 'FFFFFF',
				'h3_size' => '18',
				'h3_font_style' => '\'G - Josefin Slab\', serif',
				'h3_font_case' => '',
				'h3_font_weight' => '',
				'h4_color' => 'FFFFFF',
				'h4_size' => '16',
				'h4_font_style' => '\'G - Josefin Slab\', serif',
				'h4_font_case' => '',
				'h4_font_weight' => '',
				'h5_color' => 'FFFFFF',
				'h5_size' => '14',
				'h5_font_style' => '\'G - Josefin Slab\', serif',
				'h5_font_case' => '',
				'h5_font_weight' => '',
				'link_color' => 'ebdfd9',
				'link_hover_color' => 'ff8661',
				'link_hover_style' => 'underline',
				'sidebar_font_color' => 'E1E1E1',
				'sidebar_font_size' => '12',
				'sidebar_font_style' => 'Verdana, Arial, Helvetica, sans-serif',
				'sidebar_bg_color' => 'transparent',
				'sidebar_link_color' => 'd6874e',
				'sidebar_link_hover_color' => 'f04916',
				'sidebar_link_hover_style' => 'underline',
				'sidebar_title_color' => 'FFFFFF',
				'sidebar_title_size' => '14',
				'sidebar_title_style' => 'Arial, Helvetica, sans-serif',
				'menu_style' => 'color',
				'menu_color' => '',
				'menu_hover_color' => 'f04a16',
				'menu_font_size' => '12',
				'menu_font_style' => 'Arial, Helvetica, sans-serif',
				'menu_font_color' => 'd6874e',
				'menu_font_hover_color' => 'FFFFFF',
				'menu_font_case' => '',
				'submenu_color' => 'E8E8E8',
				'submenu_hover_color' => 'f04a16',
				'submenu_font_size' => '12',
				'submenu_font_style' => 'Arial, Helvetica, sans-serif',
				'submenu_font_color' => '333333',
				'submenu_font_hover_color' => 'FFFFFF',
				'submenu_font_case' => '',
				'nextgen_border' => '2',
				'nextgen_border_color' => 'faf7f7',
				'custom_logo' => 'title',
				'custom_logo_image' => 'Logo_Bokeh.png',
				'footer_copy' => '',
				'custom_sidebar' => 'OFF',
				'custom_sidebar_position' => 'ABOVE',
				'custom_sidebar_html' => '',
				'social_media' => 'OFF',
				'social_media_title' => 'Follow Me',
				'social_media_set' => 'small',
				'social_rss' => '',
				'social_email' => '',
				'social_twitter' => '',
				'social_facebook' => '',
				'social_flickr' => '',
				'google_analytics' => '',
				'custom_css' => '.menu a:link, .menu a:visited {
padding:52px 17px 29px;
}

#footer {
border-top:0;
}',
				'header_height' => '120',
				'header_logo_margin_above' => '10',
				'header_logo_margin_below' => '10',
				'title_size' => '30',
				'title_color' => 'd6874e',
				'title_font_style' => '',
				'title_font_weight' => '',
				'title_style' => '\'G - Josefin Slab\', serif',
				'description_size' => '16',
				'description_color' => '999999',
				'description_style' => '\'G - Josefin Slab\', serif',
				'bg_top_offset' => '0',
				'container_padding' => '20',
				'footer_font' => '12',
				'footer_font_color' => '333333',
				'custom_setting' => '',
				'footer_widget_placement' => '3',
				'footer_background' => 'FFFFFF',
				'footer_font_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'footer_widget_title' => '16',
				'footer_widget_color' => 'd6874e',
				'footer_widget_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'footer_link_color' => 'd6874e',
				'footer_link_hover_color' => 'd6874e',
				'footer_link_hover_style' => 'none',
				'footer_height' => '250',
				'show_photocrati' => '',
				'page_comments' => 'OFF',
				'blog_meta' => '',		
			),
			'PRESET.preset-bokeh'
		))
	);

	PhotocratiTheme_Preset::register(
		'photocrati.preset-prime',
		'Photocrati Prime',
		null,
		PhotocratiTheme_StyleProvider::get(PhotocratiTheme_OptionProviderList::get(
			array(
				'dynamic_style' => 'YES',
				'one_column' => 'OFF',
				'one_column_color' => 'FFFFFF',
				'one_column_logo' => 'OFF',
				'one_column_margin' => '30',
				'display_sidebar' => 'YES',
				'content_width' => '74',
				'sidebar_width' => '26',
				'logo_menu_position' => 'right-left',
				'bg_color' => 'f5dddb',
				'bg_image' => 'pink_stripes.gif',
				'bg_repeat' => 'repeat',
				'header_bg_color' => 'FFFFFF',
				'header_bg_image' => 'header_fadepink.gif',
				'header_bg_repeat' => 'repeat-x',
				'container_color' => 'ffffff',
				'container_border' => '0',
				'container_border_color' => 'CCCCCC',
				'font_color' => '000000',
				'font_size' => '14',
				'font_style' => '\"Times New Roman\", Times, serif',
				'p_line' => '20',
				'p_space' => '10',
				'h1_color' => 'e3628b',
				'h1_size' => '24',
				'h1_font_style' => '\'G - Josefin Slab\', serif',
				'h1_font_case' => '',
				'h1_font_weight' => '',
				'h1_font_align' => '',
				'h2_color' => 'e3628b',
				'h2_size' => '22',
				'h2_font_style' => '\'G - Josefin Slab\', serif',
				'h2_font_case' => '',
				'h2_font_weight' => '',
				'h3_color' => 'e3628b',
				'h3_size' => '18',
				'h3_font_style' => '\'G - Josefin Slab\', serif',
				'h3_font_case' => '',
				'h3_font_weight' => '',
				'h4_color' => 'e3628b',
				'h4_size' => '16',
				'h4_font_style' => '\'G - Josefin Slab\', serif',
				'h4_font_case' => '',
				'h4_font_weight' => '',
				'h5_color' => 'e3628b',
				'h5_size' => '14',
				'h5_font_style' => '\'G - Josefin Slab\', serif',
				'h5_font_case' => '',
				'h5_font_weight' => '',
				'link_color' => 'd1a1ac',
				'link_hover_color' => 'ff548d',
				'link_hover_style' => 'none',
				'sidebar_font_color' => '858085',
				'sidebar_font_size' => '12',
				'sidebar_font_style' => '\"Times New Roman\", Times, serif',
				'sidebar_bg_color' => 'eeeadf',
				'sidebar_link_color' => 'c6869a',
				'sidebar_link_hover_color' => 'e3628b',
				'sidebar_link_hover_style' => 'none',
				'sidebar_title_color' => 'c6869a',
				'sidebar_title_size' => '14',
				'sidebar_title_style' => 'Arial, Helvetica, sans-serif',
				'menu_style' => 'transparent',
				'menu_color' => 'FFFFFF',
				'menu_hover_color' => 'FFFFFF',
				'menu_font_size' => '12',
				'menu_font_style' => 'Arial, Helvetica, sans-serif',
				'menu_font_color' => 'd1a1ac',
				'menu_font_hover_color' => 'e3628b',
				'menu_font_case' => '',
				'submenu_color' => 'eeeadf',
				'submenu_hover_color' => 'ffffff',
				'submenu_font_size' => '12',
				'submenu_font_style' => 'Arial, Helvetica, sans-serif',
				'submenu_font_color' => 'c6869a',
				'submenu_font_hover_color' => 'e3628b',
				'submenu_font_case' => '',
				'nextgen_border' => '5',
				'nextgen_border_color' => 'e8e7e7',
				'custom_logo' => 'title',
				'custom_logo_image' => 'Logo_Pink.png',
				'footer_copy' => '',
				'custom_sidebar' => 'OFF',
				'custom_sidebar_position' => 'ABOVE',
				'custom_sidebar_html' => '',
				'social_media' => 'OFF',
				'social_media_title' => 'Follow Me',
				'social_media_set' => 'small',
				'social_rss' => '',
				'social_email' => '',
				'social_twitter' => '',
				'social_facebook' => '',
				'social_flickr' => '',
				'google_analytics' => '',
				'custom_css' => 'div.slideshow {
margin-bottom: 20px;
}

#primary {
padding:25px 23px;
width:79%;
}',
				'header_height' => '120',
				'header_logo_margin_above' => '10',
				'header_logo_margin_below' => '10',
				'title_size' => '30',
				'title_color' => 'd1a1ac',
				'title_font_style' => '',
				'title_font_weight' => '',
				'title_style' => '\'G - Josefin Slab\', serif',
				'description_size' => '16',
				'description_color' => '999999',
				'description_style' => '\'G - Josefin Slab\', serif',
				'bg_top_offset' => '0',
				'container_padding' => '30',
				'footer_font' => '12',
				'footer_font_color' => '333333',
				'custom_setting' => '',
				'footer_widget_placement' => '3',
				'footer_background' => 'FFFFFF',
				'footer_font_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'footer_widget_title' => '16',
				'footer_widget_color' => 'd1a1ac',
				'footer_widget_style' => 'Georgia, \"Times New Roman\", Times, serif',
				'footer_link_color' => 'd1a1ac',
				'footer_link_hover_color' => 'd1a1ac',
				'footer_link_hover_style' => 'none',
				'footer_height' => '250',
				'show_photocrati' => '',
				'page_comments' => 'OFF',
				'blog_meta' => '',		
			),
			'PRESET.preset-prime'
		))
	);
}

?>
