<?php
/*
WARNING!!
This is a dynamically generated style sheet that is controlled by the Wordpress admin
"Theme Options" area. We suggest that you do not edit this file. If you would like to
use your own custom styles you can override the dynamic styling in the Wordpress admin
and use the standard style sheet provided with your theme located in your theme directory
called style.css.
*/

define('ABSPATH', dirname(dirname(dirname(dirname(dirname(__FILE__))))).'/');
include_once(ABSPATH.'wp-config.php');
include_once(ABSPATH.'wp-load.php');
include_once(ABSPATH.'wp-includes/wp-db.php');
$fonts = Photocrati_Fonts::get_instance();

@header( 'Content-type: text/css' );

global $wpdb;

// Get styles from preset
$preset = Photocrati_Style_Manager::get_active_preset();
extract($preset->to_array());

$global = $wpdb->get_row("SELECT albuml_line_size FROM ".$wpdb->prefix."photocrati_gallery_settings WHERE id = 1", ARRAY_A);
foreach ($global as $key => $value) {
    $$key = $value;
}

$estyle = $wpdb->get_row("SELECT ecomm_back_color,ecomm_font_color,ecomm_line_color,ecomm_line_size,ecomm_but_color,ecomm_buttext_color,ecomm_butborder_color FROM ".$wpdb->prefix."photocrati_ecommerce_settings WHERE id = 1", ARRAY_A);
foreach ($estyle as $key => $value) {
    $$key = $value;
}
?>

    /* Reset default browser styles */
    @import url('resets/reset.css');

    /* Rebuild default browser styles */
    @import url('resets/rebuild.css');

    /* Basic WordPress Styles */
    @import url('resets/wp.css');

    /* General Styles
    -------------------------------------------------------------- */

    /* The following section sets the basic body, H1-H5 and link styles */

    html {
    height			:	100%;
    }

    body {
    background		: 	<?php if($bg_image <> '') { ?>url(../images/uploads/<?php echo $bg_image; ?>) <?php echo $bg_repeat; ?><?php } ?> 0 <?php echo $bg_top_offset; ?>px #<?php echo $bg_color; ?>;
    padding-top 	: 	0;
    margin-top 		: 	0;
    height			:	100%;
    }

    h1 { /* The H1 tag is used for page titles, and post titles on blog page. */
    font-size 		: 	<?php echo $h1_size; ?>px;
    font-family		:	<?php echo $fonts->get_css_value($h1_font_style)?>;
    color			: 	#<?php echo $h1_color; ?>;
    text-decoration :   <?php echo $h1_font_decoration ?>;
    clear			:	none;
<?php if($h1_font_case != 'none') { ?>
    text-transform	:	<?php echo $h1_font_case ?>;
<?php } ?>
<?php if($h1_font_weight) { ?>
    font-weight		:	<?php echo $h1_font_weight?>;
<?php } ?>
<?php if ($h1_font_italic): ?>
    font-style      :   <?php echo $h1_font_italic ?>;
<?php endif ?>
<?php if($h1_font_align == 'center') { ?>
    text-align		:	center;
<?php } ?>
    }

    h1 a:link, .h1 a:active, .h1 a:visited {
    color			: 	#<?php echo $h1_color; ?>;
    }

    div.post h1.entry-title a {
    color			: 	#<?php echo $h1_color; ?>;
    }

    h2 { /* The H2 tag is used for post titles */
    font-size 		: 	<?php echo $h2_size; ?>px;
    font-family		:	<?php echo $fonts->get_css_value($h2_font_style)?>;
    color			: 	#<?php echo $h2_color; ?>;
    text-decoration :   <?php echo $h2_font_decoration ?>;
    clear			:	none;
<?php if ($h2_font_case != 'none'): ?>
    text-transform  :   <?php echo $h2_font_case ?>;
<?php endif ?>
<?php if($h2_font_weight): ?>
    font-weight		:	<?php echo $h2_font_weight ?>;
<?php endif ?>
<?php if ($h2_font_italic): ?>
    font-style      :   <?php echo $h2_font_italic ?>;
<?php endif ?>
<?php if($h2_font_align == 'center') { ?>
    text-align		:	center;
<?php } ?>
    margin-top      :	20px;
    margin-bottom   :   15px;
    }

    h2 a:link, .h2 a:active, .h2 a:visited {
    color			: 	#<?php echo $h2_color; ?>;
    }

    div.post h2.entry-title a {
    color			: 	#<?php echo $h2_color; ?>;
    }

    h3 {
    font-size 		: 	<?php echo $h3_size; ?>px;
    font-family     :   <?php echo $fonts->get_css_value($h3_font_style) ?>;
    color			: 	#<?php echo $h3_color; ?>;
    text-decoration :   <?php echo $h3_font_decoration ?>;
    clear			:	none;
<?php if ($h3_font_case != 'none'): ?>
    text-transform  :   <?php echo $h3_font_case ?>;
<?php endif ?>
<?php if ($h3_font_weight): ?>
    font-weight     :   <?php echo $h3_font_weight ?>;
<?php endif ?>
<?php if ($h3_font_italic): ?>
    font-style      :   <?php echo $h3_font_italic ?>;
<?php endif ?>
<?php if($h3_font_align == 'center') { ?>
    text-align		:	center;
<?php } ?>
    margin-top		:	20px;
    margin-bottom	:	15px;
    }

    h3 a:link, .h1 a:visited {
    color			: 	#<?php echo $h3_color; ?>;
    }

    h4 {
    font-size 		: 	<?php echo $h4_size; ?>px;
    font-family     :   <?php echo $fonts->get_css_value($h4_font_style) ?>;
    color			: 	#<?php echo $h4_color; ?>;
    text-decoration :   <?php echo $h4_font_decoration ?>;
    clear			:	none;
<?php if ($h4_font_case != 'none'): ?>
    text-transform  :   <?php echo $h4_font_case ?>;
<?php endif ?>
<?php if ($h4_font_weight): ?>
    font-weight		:	<?php echo $h4_font_weight ?>;
<?php endif ?>
<?php if ($h4_font_italic): ?>
    font-style      :   <?php echo $h4_font_italic ?>;
<?php endif ?>
<?php if($h4_font_align == 'center') { ?>
    text-align		:	center;
<?php } ?>
    margin-top		:	20px;
    margin-bottom	:	15px;
    }

    h4 a:link, .h4 a:visited {
    color			: 	#<?php echo $h4_color; ?>;
    }

    h5 {
    font-size 		: 	<?php echo $h5_size; ?>px;
    font-family     :   <?php echo $fonts->get_css_value($h5_font_style) ?>;
    text-decoration :   <?php echo $h5_font_decoration ?>;
    color			: 	#<?php echo $h5_color; ?>;
    clear			:	none;
<?php if ($h5_font_case != 'none'): ?>
    text-transform  :   <?php echo $h5_font_case ?>;
<?php endif ?>
<?php if($h5_font_weight) { ?>
    font-weight		:	<?php echo $h5_font_weight ?>;
<?php } ?>
<?php if ($h5_font_italic): ?>
    font-style      :   <?php echo $h5_font_italic ?>;
<?php endif ?>
<?php if($h5_font_align == 'center') { ?>
    text-align		:	center;
<?php } ?>
    margin-top		:	20px;
    margin-bottom	:	15px;
    }

    h5 a:link, .h5 a:visited {
    color			: 	#<?php echo $h5_color; ?>;
    }

    a:link,a:visited { /* This styles the majority of the on page links. The sidebar links can be styled seperately */
    color 			: 	#<?php echo $link_color; ?>;
    text-decoration : 	none;
    }

    a:hover,a:active {
    color 			: 	#<?php echo $link_hover_color; ?>;
    text-decoration : 	<?php echo $link_hover_style; ?>;
    }

    .clear {
    width			:	100%;
    clear			:	both;
    height			:	1px;
    }


    /* General Page Styles
    -------------------------------------------------------------- */

    #main_container {
    min-height		:	100%;
    z-index			:	-1;
<?php if($one_column) { ?>
    width			:	960px;
    padding			:	0 15px;
    margin			:	0 auto;
    background		:	#<?php echo $one_column_color; ?>;
<?php } ?>
    }

    #wrapper { /* This sets the width of the entire site */
    position 		: 	relative;
    width 			: 	960px;
    margin 			: 	0 auto;
    overflow		:	auto;
    padding-bottom	:	<?php echo $footer_height; ?>px;
    }

    #container { /* This sets the width of the main content area */
    float			: 	left;
    margin			: 	0 0 15px 0;
    width			: 	<?php echo 960 - ((int)$container_padding * 2) - ((int)$container_border * 2); ?>px;
    padding			: 	<?php echo $container_padding; ?>px;
    background		: 	<?php if($container_color <> 'transparent') { echo '#'; } ?><?php echo $container_color; ?>;
    border			:	<?php echo $container_border; ?>px solid #<?php echo $container_border_color; ?>;
    }

    .home #container { /* Correctly positions the content container no the home page */
    margin:  0px 0 15px 0;
    }
    .home.blog #container {
    margin-top: 0px;
    }

    /* Menu Styles
    -------------------------------------------------------------- */

    #menu_wrapper { /* This is the main menu container */
<?php if($logo_menu_position == 'left-right') { ?>
    width 			: 	955px;
    <?php if($one_column_logo) { ?>
        margin			: 	<?php echo $one_column_margin; ?>px 0 0 0;
    <?php } else { ?>
        margin			: 	30px 0 0 0;
    <?php } ?>
    float 			: 	right;
    text-align 		: 	right;
    position		:	absolute;
<?php } else if($logo_menu_position == 'right-left') { ?>
    width 			: 	650px;
    <?php if($one_column_logo) { ?>
        margin			: 	<?php echo $one_column_margin; ?>px 0 0 0;
    <?php } else { ?>
        margin			: 	30px 0 0 0;
    <?php } ?>
    float 			: 	left;
    text-align 		: 	left;
    position		:	absolute;
<?php } else if($logo_menu_position == 'bottom-top') { ?>
    width 			: 	100%;
    margin			: 	0 0 1.5em 0;
    position 		: 	absolute;
    top 			: 	0;
    left 			: 	0;
    text-align 		: 	center;
<?php } else if($logo_menu_position == 'top-bottom') { ?>
    width 			: 	100%;
    margin			: 	0 0 1.5em 0;
    clear			:	both;
    text-align 		: 	center;
    position		:	absolute;
    left			:	0;
    top				:	<?php echo ($header_height - 50); ?>px;;
<?php } ?>
    overflow 		: 	visible;
    padding-top 	: 	22px;
<?php if($logo_menu_position == 'right-left') { ?>
    z-index			:	4;
<?php } else { ?>
    z-index			:	2;
<?php } ?>
    }

    .menu ul, .menu ul * { /* This sets the width of the menu */
    list-style		: 	none;
    margin			: 	0 0 0 0;
    padding			:	0;
    }

    .menu ul { /* This sets the line height of the menu */
    line-height		:	1.0;
    }

    .menu a { /* This controls the font size and position of the main menu links */
    position		:	relative;
    display			: 	block;
    float			: 	left;
    font-size 		: 	<?php echo $menu_font_size; ?>px;
<?php if($menu_font_case == '' || $menu_font_case == 'uppercase') { ?>
    text-transform	:	uppercase;
<?php } ?>
    }

    .menu a:link,.menu a:visited { /* This sets the color and style of the main menu links */
    display 		: 	inline;
    float 			: 	none;
    color 			: 	#<?php echo $menu_font_color; ?>;
    font-family     :   <?php echo $fonts->get_css_value($menu_font_style) ?>;
<?php if ($menu_font_weight): ?>
    font-weight     :   <?php echo $menu_font_weight ?>;
<?php endif ?>
<?php if ($menu_font_italic): ?>
    font-style:     :    <?php echo $menu_font_italic ?>;
<?php endif ?>
    text-decoration :   <?php echo $menu_font_decoration ?>;
    padding 		: 	22px 17px 12px 17px;
    background 		: 	<?php if($menu_style <> 'transparent') { echo '#'.$menu_color; } else { echo $menu_style; } ?>;
    }

    .menu a:hover,.menu a:active,
    .menu .current_page_item a:link,
    .menu .current_page_item a:visited  { /* This sets the color and style of the hover and active states of the main menu links */
    color 			: 	#<?php echo $menu_font_hover_color; ?>;
    background 		: 	<?php if($menu_style <> 'transparent') { echo '#'.$menu_hover_color; } else { echo $menu_style; } ?>;
    }

    .menu .current_page_item ul a:link,
    .menu .current_page_item ul a:visited { /* This sets the color and style of the current page item on the main menu links */
    color 			: 	#<?php echo $menu_font_hover_color; ?>;
    background 		: 	#<?php echo $menu_hover_color; ?>;
    }

    .menu .current_page_item ul li a:hover,
    .menu .current_page_item ul li a:active { /* This sets the color and style of the hover and active states of the current page item on the main menu links */
    color 			: 	#<?php echo $menu_font_hover_color; ?>;
    background 		: 	#<?php echo $menu_hover_color; ?>;
    }

    .menu ul li { /* This sets the position of the main menu items */
    position		:	relative;
    display			: 	inline;
    margin			:	0 0 0 0;
    }

    .menu ul li { /* This sets the position of the custom main menu items */
    position		:	relative;
    display			: 	inline;
    margin			:	0 -3px 0 0;
    }

    .menu ul li:hover {
    visibility		:	inherit; /* fixes IE7 'sticky bug' */
    }

    .menu ul li ul { /* This sets the position of the dropdown menu */
    display			:	block;
    visibility		:	hidden;
    position		:	absolute;
    top				:	-999em;
    margin			:	0 0 0 0;
    width			:	10em; /* left offset of submenus need to match (see below) */
    }

    .menu ul li:hover ul,
    .menu ul li ul { /* This sets the position and z-index of the dropdown menu */
    left			:	0;
    top				:	2.2em; /* match top ul list item height */
    z-index			:	99;
    }

    .menu ul li ul li { /* This sets the size and transparency of the dropdown items */
    display 		: 	block;
    width			:	100%;
    filter			:	alpha(opacity=90);
    opacity			: 	0.90;
    -moz-opacity	:	0.90;
    margin			:	0;
    }

    .menu ul li ul li a:link,
    .menu ul li ul li a:visited,
    .menu ul li.current_page_item ul li a:link,
    .menu ul li.current_page_item ul li a:visited { /* This sets the color and style of the drop down menu links */
    display 		: 	block;
    padding 		: 	5px;
    text-align 		: 	left;
    color 			: 	#<?php echo $submenu_font_color; ?>;
    background 		: 	#<?php echo $submenu_color; ?>;
    font-size 		: 	<?php echo $submenu_font_size; ?>px;
    font-family     :   <?php echo $fonts->get_css_value($submenu_font_style) ?>;
<?php if ($submenu_font_case == '') $submenu_font_case = 'uppercase'; ?>
    text-transform  :   <?php echo $submenu_font_case ?>;
    text-decoration :   <?php echo $submenu_font_decoration ?>;
<?php if ($submenu_font_weight): ?>
    font-weight:    :   <?php echo $submenu_font_weight ?>;
<?php endif ?>
<?php if ($submenu_font_italic): ?>
    font-style      :   <?php echo $submenu_font_italic ?>;
<?php endif ?>
    }

    .menu ul li ul li a:hover,
    .menu ul li ul li a:active,
    .menu ul li.current_page_item ul li a:hover,
    .menu ul li.current_page_item ul li a:active,
    .menu ul li ul li.current_page_item a:link,
    .menu ul li ul li.current_page_item a:visited { /* This sets the color and style of the hover, active & current states of the drop down menu links */
    color 			: 	#<?php echo $submenu_font_hover_color; ?>;
    background 		: 	#<?php echo $submenu_hover_color; ?>;
    }

    /* The remaining items below are essential positioning styles for the menus */

    .menu ul li:hover li ul,
    .menu ul li li ul {
    top				:	-999em;
    }

    .menu ul li li:hover ul,
    .menu ul li li ul {
    left			:	10em; /* match ul width */
    top				:	0;
    }

    .menu ul li li:hover li ul,
    .menu ul li li li ul {
    top				:	-999em;
    }

    .menu ul li li li:hover ul,
    .menu ul li li li ul {
    left			:	10em; /* match ul width */
    top				:	0;
    }

    .footer_menu { /* This sets the z-index of the footer menu */
    z-index			:	2;
    }

    .footer_menu ul, .footer_menu ul * { /* This sets the width of the footer menu */
    overflow 		: 	visible;
    z-index			:	2;
    list-style		: 	none;
    margin			:	0 auto;
    padding			:	0;
    }

    .footer_menu ul li { /* This sets the position of the footer menu items */
    position		:	relative;
    display			: 	inline;
    margin			:	0 7px 0 7px;
    font-weight		:	bold;
    text-transform	: 	uppercase;
    font-size		: 	14px;
    }


    /* Header Styles
    -------------------------------------------------------------- */

    #header { /* This sets the color of the header */
    background		:	<?php if($header_bg_image <> '') { ?>url(../images/uploads/<?php echo $header_bg_image; ?>) bottom <?php echo $header_bg_repeat; ?><?php } ?> #<?php echo $header_bg_color; ?>;
<?php if($one_column) { ?>
    width			:	990px;
    position		:	relative;
    left			:	-15px;
<?php } else { ?>
    width			: 	100%;
<?php } ?>
    height			:	<?php echo $header_height; ?>px;
    margin-bottom	:	10px;
    }

    #masthead { /* This sets total width and position of the header */
    width			:	960px;
    margin			:	0 auto;
    position        :   relative; /* need to fix menu position in IE */
    }

    #branding { /* This sets the size and position of the logo area on the header */
    display			:	block;
<?php if($logo_menu_position == 'left-right') { ?>
    float 			: 	left;
    margin			:	0;
    position		:	relative;
    <?php if($one_column_logo) { ?>
        left			:	-15px;
        width 			: 	990px;
    <?php } else { ?>
        width 			: 	400px;
    <?php } ?>
    z-index			:	3;
<?php } else if($logo_menu_position == 'right-left') { ?>
    float 			: 	right;
    text-align		:	right;
    <?php if($one_column_logo) { ?>
        width 			: 	990px;
        left			:	15px;
    <?php } else { ?>
        width 			: 	950px;
    <?php } ?>
    margin			:	0;
    position		:	relative;
    z-index			:	3;
<?php } else if($logo_menu_position == 'bottom-top') { ?>
    width 			: 	100%;
    text-align 		: 	center;
    <?php if($one_column_logo) { ?>
        position		:	relative;
        left			:	-15px;
    <?php } ?>
    margin			:	0 0 24px 0;
<?php } else if($logo_menu_position == 'top-bottom') { ?>
    width 			: 	100%;
    text-align 		: 	center;
    <?php if($one_column_logo) { ?>
        position		:	relative;
        left			:	-15px;
    <?php } ?>
    margin			:	0 0 5px 0;
<?php } ?>
    padding			:	<?php echo $header_logo_margin_above; ?>px 0 <?php echo $header_logo_margin_below; ?>px 0;
    }

    #branding a { /* This sets the color and style of the wordpress title */
    text-decoration	:	none;
    }

    #branding h1 { /* This sets the color of the wordpress title */
    font-size		:	<?php echo $title_size; ?>px;
    font-family     :   <?php echo $fonts->get_css_value($title_style) ?>;
    color			: 	#<?php echo $title_color; ?>;
    line-height		:	<?php echo $title_size + 2; ?>px;
    border			:	0;
    margin-top		:	15px;
    margin-bottom	:	5px;
    padding			:	0;
<?php if($logo_menu_position == 'left-right') { ?>
    text-align		:	left;
<?php } else if($logo_menu_position == 'right-left') { ?>
    text-align		:	right;
<?php } else { ?>
    text-align		:	center;
<?php } ?>
<?php if($title_font_case == 'uppercase') { ?>
    text-transform	:	uppercase;
<?php } else { ?>
    text-transform	:	none;
<?php } ?>
<?php if($title_font_weight) { ?>
    font-weight		:	<?php echo $title_font_weight ?>;
<?php } ?>
<?php if ($title_italic): ?>
	font-style      :   italic;
<?php endif ?>
    }

    #branding .description { /* This sets the font size and color for the description line if you are using the Wordpress title and description */
    font-size		:	<?php echo $description_size; ?>px;
    font-family     :   <?php echo $fonts->get_css_value($description_style) ?>;
    color			: 	#<?php echo $description_color; ?>;
<?php if ($description_font_style == 'uppercase'): ?>
    text-transform  :   uppercase;
<?php endif ?>
    text-decoration :   <?php echo $description_font_decoration ?>;
<?php if ($description_font_weight): ?>
    font-weight     :   <?php echo $description_font_weight ?>;
<?php endif ?>
<?php if ($description_font_italic): ?>
    font-style      :   <?php echo $description_font_italic ?>;
<?php endif ?>
<?php if($logo_menu_position == 'left-right') { ?>
    margin-left		:	3px;
<?php } ?>
<?php if($logo_menu_position == 'right-left') { ?>
    margin-right	:	5px;
<?php } ?>
    }


    /* Content Styles
    -------------------------------------------------------------- */

    #content { /* This sets the width of the page content area  */
    position		:	relative;
    margin			: 	0;
    width			:	100%;
    z-index			:	1;
    }

    #content-sm { /* This sets the width of the blog content area  */
<?php if ($preset->is_sidebar_enabled()): ?>
    width			:	<?php echo (int)$content_width - 5; ?>%;
    float			:	left;
<?php else: ?>
    width			:	<?php echo (int)$content_width; ?>%;
    float			:	left;
<?php endif ?>
    }

    #content, #content-sm { /* This sets the font size and style on the blog and pages  */
    color 			: 	#<?php echo $font_color; ?>;
    font-size		: 	<?php echo $font_size; ?>px;
    font-family     :   <?php echo $fonts->get_css_value($font_style) ?>;
    text-decoration :   <?php echo $font_decoration ?>;
<?php if ($font_weight): ?>
    font-weight     :   <?php echo $font_weight ?>;
<?php endif ?>
<?php if ($font_italic): ?>
    font-style      :   <?php echo $font_italic ?>;
<?php endif ?>
<?php if ($font_case != 'none'): ?>
    text-transform  :   <?php echo $font_case ?>;
<?php endif ?>
    }

    #content p, #content-sm p { /* This sets the paragraph spacing and line height  */
    line-height		: 	<?php echo $p_line; ?>px;
    margin-bottom	: 	<?php echo $p_space; ?>px;
    }

    p {
    margin-bottom	:	0.5em;
    }

    .post { /* This sets a small margin at the bottom of posts  */
    margin			: 	0 0 3em 0;
    }

    #nav-above { /* This hides the navigation above blog posts*/
    display			:	none;
    }

    #nav-above, #nav-below { /* Styles post navigation that appears above and below blog posts. */
    font-family			: 	'Open Sans', sans-serif;
    }

    .entry-content, .entry-summary { /* This sets a small margin at the top of the post content to make space between the title/meta area  */
    margin			: 	1.5em 0 0 0;
    }

    blockquote { /* This styles blockquotes in blog posts  */
    border-left		:	2px solid #E1E1E1;
    margin-left		:	25px;
    padding-left	:	15px;
    }


    /* Post Styles
    -------------------------------------------------------------- */

    .navigation { /* This sets a small margin below the post navigation on a single post */
    margin			: 	0 0 1.5em 0;
    overflow		: 	auto;
    }

    .size-full,
    .entry-content img { /* This sets a border around images in posts */
    border 			: 	5px solid #e8e7e7;
    }

    .entry-meta,
    .entry-utility { /* This sets the font size and style on post meta. This is the date, post by and comment links below the post title. */
    color 			: 	#<?php echo $font_color; ?>;
    font-size		: 	<?php echo $font_size; ?>px;
    font-family     :   <?php echo $fonts->get_css_value($font_style) ?>;
    font-style 		: 	normal;
    text-transform	:	uppercase;
    font-size		: 	10px;
    clear 			: 	both;
    }

    .entry-meta {
    padding-left	: 	4px;
    }

    div.entry-date, .month, .day, .year { /* This aligns the post date on one line rather than stacked on top of each other. */
    display			: 	inline;
    }

    .entry-utility { /* This styles the blog post footer meta. */
    border-top		: 	1px solid #999;
    }


    /* Post Comment Styles
    -------------------------------------------------------------- */

    .comments ol { /* This removes the numbers from the comment list */
    list-style		:	none;
    margin-top		:	10px;
    }

    .comments li { /* This clears each comment block to a new line and adds a margin */
    width			:	100%;
    clear			:	both;
    min-height		:	100px;
    }

    .comments ul.children { /* This clears each comment block to a new line and adds a margin */
    list-style		:	none;
    margin-top		:	30px;
    }

    .comments .comment-wrapper { /* This sets the style for the comment wrapper */
    display			:	block;
    }

    p#comment-notes {
    font-size		: 	13px;
    }

    div.comment-meta a.commentauthor:link, a.commentauthor:visited { /* This styles the comment author name text. */
    color			: 	#3e3e3e;
    }

    .comments .comment-author { /* This sets the style for the comment author icon */
    float			:	left;
    width			:	13%;
    margin-right	:	4%;
    }

    .comment-author img { /* This sets the size of comment avatars */
    width			: 	65px;
    height			: 	65px;
    }

    .comments .content-wrapper { /* This sets the style for the comment meta and content */
    float			:	left;
    width			:	83%;
    }

    .comments .comment-content { /* This sets a small margin between the meta and comment content */
    margin-top		:	5px;
    margin-bottom	: 	40px;
    }

    .comment-content { /* This styles the bottom of the comment text. */
    border-bottom	: 	1px solid #e1e1e1;
    }

    div.comment-meta { /* This is the comment author, date and permalink styles. */
    line-height		: 	1;
    padding-bottom	: 	15px;
    }

    div.comment-meta a.commentauthor:link, a.commentauthor:visited { /* This styles the comment author name. */
    font-size		: 	18px;
    font-weight		: 	bold;
    display			: 	block;
    }

    div.comment-meta .commentdate { /* This styles the comment date. */
    font-size		: 	14px;
    color			: 	#999;
    }

    div.comment-meta .commentpermalink { /* This styles the comment permalink. */
    font-size		: 	12px;
    }

    .comment-meta, .comment-reply-link { /* This styles the comment meta and reply link */
    font-family		: 	'Open Sans', sans-serif;
    }

    .comment-reply-link { /* This styles the comment reply link. */
    float			: 	right;
    margin-top		: 	-20px;
    font-weight		: 	bold;
    font-size		: 	14px;
    }

    div#cancel-comment-reply, span.loggedin, span.logout { /* This styles the 'cancel comment reply' link, logged in and logged out link. */
    font-size		: 	13px;
    }

    div#respond { /* This styles the comment reply form. */
    padding-bottom	: 	40px;
    }

    #respond h3 { /* This styles the comment reply h3 title. */
    margin-bottom	: 	-5px;
    }

    span.unapproved {
    font-style 		: 	italic;
    }

    #comments #respond input#author, #respond input#email, #respond input#url { /* This styles the comment form. */
    background		: 	#fdfdfd;
    color			: 	#a1a1a1;
    height			: 	24px;
    border			: 	2px solid #ccc;
    }

    #comments div#form-section-comment textarea { /* This styles the comment form. */
    width			: 	100%;
    background		: 	#fdfdfd;
    color			: 	#252525;
    font-size		: 	14px;
    border			: 	2px solid #ccc;
    }

    #comments input#submit {
    background  :  #3e3e3e;
    border   :  0px;
    border-radius :  5px;
    padding   :  10px 20px;
    margin-top  :  15px;
    color   :  #fff;
    font-family  :  Open Sans, 'arial black', sans-serif;
    font-size  :  13px;
    font-weight  :  bold;
    }

    #comments input#submit:hover {
    background			: 	#<?php echo $link_color; ?>;
    cursor				:	pointer;
    }

    img.wp-smiley{  /* This sets no border around smileys */
    border			:	none;
    }


    /* Sidebar Styles
    -------------------------------------------------------------- */

    #sidebar { /* This sets the size of the sidebar as well as the font size and style */
    float			:	right;
    width			: 	<?php echo $sidebar_width; ?>%;
    padding-top		: 	13px;
    background		:	<?php if($sidebar_bg_color <> 'transparent') { echo '#'; } ?><?php echo $sidebar_bg_color; ?>;
    text-align		:	center;
    color			:	#<?php echo $sidebar_font_color; ?>;
    font-size		:	<?php echo $sidebar_font_size; ?>px;
    font-family     :   <?php echo $fonts->get_css_value($sidebar_font_style) ?>;
    text-decoration :   <?php echo $sidebar_font_decoration ?>;
<?php if ($sidebar_font_weight): ?>
    font-weight     :   <?php echo $sidebar_font_weight ?>;
<?php endif ?>
<?php if ($sidebar_font_italic): ?>
    font-style      :   <?php echo $sidebar_font_italic ?>;
<?php endif ?>
<?php if ($sidebar_font_case != 'none'): ?>
    text-transform  :   <?php echo $sidebar_font_case ?>;
<?php endif ?>
    }

    #sidebar a { /* This sets the color of the sidebar links */
    color			:	#<?php echo $sidebar_link_color; ?>;
    }

    #sidebar a:hover,
    #sidebar a:active { /* This sets the color and style of the hover and active states of the sidebar links */
    color			:	#<?php echo $sidebar_link_hover_color; ?>;
    text-decoration	:	<?php echo $sidebar_link_hover_style; ?>;
    }

    #sidebar .social-media { /* This sets the padding of the social media icons in the sidebar */
    text-align		:	left;
    padding			:	10px 10px 5px 10px;
    }

    #sidebar .social-media img { /* This sets a small margin to the right of each of the social media icons */
    border			:	0;
    margin-right	:	5px;
    }

    #primary, #primary_custom { /* This sets the position and width of the widget area */
    float   :  right;
    overflow  :  hidden;
    width    :  100%;
    padding-left : 0%;
    text-align  : left;
    }

    #sidebar #primary { /* ensures there is some padding between the border of the sidebar and it's content */
        width: 92%;
        margin: 0px auto;
        float: none;
    }

    .widget-title,.widgettitle { /* This sets the size and style of the sidebar titles */
    font-size 		: 	<?php echo $sidebar_title_size; ?>px;
    font-family     :   <?php echo $fonts->get_css_value($sidebar_title_style) ?>;
    color 			: 	#<?php echo $sidebar_title_color; ?>;
    text-decoration :   <?php echo $sidebar_title_decoration ?>;
<?php if ($sidebar_title_weight): ?>
    font-weight     :   <?php echo $sidebar_title_weight ?>;
<?php endif ?>
<?php if ($sidebar_title_italic): ?>
    font-style      :   <?php echo $sidebar_title_italic ?>;
<?php endif ?>
<?php if ($sidebar_title_case != 'none'): ?>
    text-transform  :   <?php echo $sidebar_title_case ?>;
<?php endif ?>
    margin-bottom 	: 	10px;
    padding-bottom 	: 	0;
    }

    .widget-container { /* This sets a small margin below each widget */
    margin			: 	0 0 1.5em 0;
    }

    #searchform label { /* This hides the search form label */
    display 		: 	none;
    }


    /*---------styling for custom menus in sidebar-------------*/

    .widget_nav_menu ul.menu {
    line-height		:	.5;
    }

    .widget_nav_menu ul.menu li a:link, .widget_nav_menu ul.menu li a:visited, .widget_nav_menu ul.menu li .current_page_item a:visited, .widget_nav_menu ul.menu li a:hover  {
    background		: 	transparent;
    padding-left	: 	0px;
    font-family     :   <?php echo $fonts->get_css_value($sidebar_font_style) ?>;
    font-size		:	<?php echo $sidebar_font_size; ?>px;
    line-height		:	1.5;
    padding			:	0px 0px;
    }

    .widget_nav_menu ul.menu li {
    border-bottom	: 	0px;
    }

    .widget_nav_menu ul.menu ul.sub-menu { /*-----hides sidebar custom menu submenus-----*/
    display			:	none;
    }

    /*--------search form styles--------*/
    #searchform {
    position  :  relative;
    overflow  : hidden;
    width   :  90%;
    height   :  24px;
    padding-bottom :  5px;
    padding-left :  3px;
    background  :  #fdfdfd;
    border   :  1px solid #ccc;
    /*--shadow--*/
    -moz-box-shadow: inset 0 0 3px #888;
    -webkit-box-shadow:  inset 0 0 5px #888;
    box-shadow:  inset 0 0 5px #888;
    }

    #searchform input#s{
    width   :  88%;
    height   :  24px;
    padding-top  :  3px;
    padding-bottom :  4px;
    background  :  transparent;
    border   :  0px;
    color   :  #a1a1a1;
    font-size  :  16px;
    }

    div.entry-content #searchform input#s {
    width   :  93%;
    }

    #footer-widgets #searchform {
    margin-top  :  25px;
    }

    #footer-widgets #searchform input#s {
    width   :  85%;
    }

    /*---search button----*/
    #searchsubmit {
    position  : absolute;
    width   :  24px;
    height   :  24px;
    text-indent  :  -1000em;
    background  :  transparent url('../images/search_circle.png') no-repeat scroll 0 0;
    border   : 0 none;
    top   : 3px;
    right   : 3px;
    }

    #searchsubmit:hover {
    -ms-filter  :  "progid:DXImageTransform.Microsoft.Alpha(Opacity=50)";
    filter   :  alpha(opacity=50);
    opacity   :  .5;
    cursor   : pointer;
    }

    /* The following style the lists in the widgets */

    .widget-area ul {
    list-style		: 	none;
    margin-left		: 	0;
    }

    .widget-area ul ul {
    list-style		: 	disc;
    margin-left		: 	0;
    }

    .widget-area ul ul li { /* This styles the sidebar bullet list. */
    list-style		: 	none;
    line-height		: 	2;
    padding-left	: 	0px;
    border-bottom	: 	1px dotted #ccc;
    }

    .widget-area ul ul ul {
    margin-left		: 	0px;
    }


    /* Gallery Styles
    -------------------------------------------------------------- */

    .galleria-info-text {
    }

    .galleria-info-title {
    /*color 			: 	#<?php echo $font_color; ?>;*/
    font-size		: 	<?php echo $font_size; ?>px;
    font-family     :   <?php echo $fonts->get_css_value($font_style) ?>;
    }

    .galleria-info-description {
    /*color 			: 	#<?php echo $font_color; ?>;*/
    font-size		: 	<?php echo $font_size; ?>px;
    font-family     :   <?php echo $fonts->get_css_value($font_style) ?>;
    }

    .photocrati_nojava {
    width			:	100%;
    text-align		:	center;
    margin			:	0 auto;
    }

    .photocrati_nojava img {
    max-width		:	100%!important;
    margin			:	5px auto;
    }

    .iframe_wrapper {
    width			:	100%;
    text-align		:	center;
    }

    .gallery {
    margin-bottom	:	15px;
    }

    .gallery img {
    border			:	0px;
    }


    /* Album Styles
    -------------------------------------------------------------- */

    .album_wrapper {
    width			:	100%;
    clear			:	both;
    margin-bottom	:	15px;
    }

    .album_list .image_wrapper {
    width			:	25%;
    }

    .album_list .image_wrapper img {
    max-width		:	90%;
    max-height		:	<?php echo (150 - ($albuml_line_size * 2)); ?>px;
    }

    .album_list .meta_wrapper {
    width			:	75%;
    margin-top      :   0px;
    }

    .album_list h4 {
    margin-top      :   0px;
    }


    /* E-Commerce Gallery Styles
    -------------------------------------------------------------- */

    .ecommerce_wrapper {
    width			:	100%;
    height			:	auto;
    position		:	relative;
    margin-bottom	:	10px;
    clear			:	both;
    }

    .ecommerce {
    float			:	left;
    text-align		:	center;
    }

    .ecommerce .meta_wrapper .quantity {
    width			:	40%;
    float			:	left;
    }

    .ecommerce .meta_wrapper .quantity input {
    padding			:	3px;
    border			:	1px solid #999;
    font-size		:	11px;
    }

    .addto {
    width			:	100%;
    float			:	right;
    text-align		:	right;
    }

    .addto a, a.iframe {
    text-decoration	:	none;
    }

    .addto button, button.addto, button#addto, button#addto2, button#addto3 {
    display			:	block;
    width			:	auto;
    overflow		:	visible;
    float			:	right;
    margin			:	2px 0 0 0;
    background		:   #<?php echo $ecomm_but_color; ?> url(../images/button-overlay.png) repeat-x;
    border			:	1px solid #<?php echo $ecomm_butborder_color; ?>;
    font-family		:	"Lucida Grande", Tahoma, Arial, Verdana, sans-serif;
    font-size		:	11px;
    line-height		:	130%;
    text-decoration	:	none;
    font-weight		:	bold;
    color			:	#<?php echo $ecomm_buttext_color; ?>;
    cursor			:	pointer;
    padding			:	3px 5px; /* Links */
    -moz-border-radius	: 	8px;
    border-radius	: 	8px;
    }

    button#addto2 {
    padding			:	5px 5px 5px 22px; /* Links */
    }

    .addto button img, button#addto2 img {
    border			:	0;
    clear			:	none;
    position		:	absolute;
    margin-left		:	-17px;
    }

    .addto img {
    margin			:	0 3px -1px 0 !important;
    padding			:	0;
    border			:	none;
    cursor			:	pointer;
    }


    /* E-Commerce Add to Cart Window
    -------------------------------------------------------------- */
    .ecommerce_lightbox #fancybox-overlay{
        overflow: hidden;
    }
    .ecommerce_lightbox #fancybox-content {
    -webkit-overflow-scrolling: touch !important;
    overflow: scroll !important;
    }

    #cart_wrapper {
    width			:	98%;
    }

    .cart_header {
    width			:	100%;
    padding			:	3px 6px;
    background		:	#<?php echo $ecomm_back_color; ?>;
    color			:	#<?php echo $ecomm_font_color; ?>;
    font-size		:	13px;
    border			:	1px solid #<?php echo $ecomm_line_color; ?>;
    border-left		:	0;
    border-right	:	0;
    }

    .cart_image {
    width			:	30%;
    float			:	left;
    margin-top      :   10px;
    }

    #shopping_cart_wrapper .cart_image {
    margin-top      :   0px;
    }


    .checkout_fields_table {
    width           :   82%;
    float           :   left;
    }


    .checkout_fields_table th {
    text-align      :   right;
    padding-right   :   5px;
    }

    .checkout_fields_table td {
    text-align: left;
    }

    .checkout_fields_table .textfield {
    width           :   100%;
    }

    .cart_image img {
    max-width		:	<?php echo (175-($ecomm_line_size*2)); ?>px;
    border			:	<?php echo $ecomm_line_size; ?>px solid #<?php echo $ecomm_line_color; ?>;
    }

    .cart_data {
    width			:	70%;
    float			:	left;
    font-size		:	13px;
    }

    .cart_qty, .cart_desc, .cart_amt, .cart_line {
    float			:	left;
    margin			:	2px 0;
    height			:	30px;
    font-size		:	12px;
    }

    .cart_qty {
    width			:	15%;
    }

    .cart_qty input {
    width			:	35px;
    padding			:	2px;
    border			:	1px solid #<?php echo $ecomm_line_color; ?>;
    font-size		:	12px;
    }

    .cart_desc {
    width			:	49%;
    padding-top		:	5px;
    }

    .cart_amt {
    width			:	18%;
    padding-top		:	5px;
    }

    .cart_line {
    width			:	18%;
    padding-top		:	2px;
    }

    .cart_line input {
    width			:	55px;
    border			:	0;
    padding			:	0;
    font-size		:	12px;
    }

    .cart_clear {
    border-bottom	:	1px solid #<?php echo $ecomm_line_color; ?>;
    margin-bottom	:	6px;
    }

    .cart_total {
    width			:	82%;
    font-weight		:	bold;
    float			:	left;
    padding-top		:	3px;
    font-size		:	12px;
    }

    .cart_total_amount {
    width			:	18%;
    float			:	left;
    font-size		:	12px;
    }

    .cart_total_amount input {
    width			:	55px;
    border			:	0;
    padding			:	0;
    font-size		:	12px;
    }

    .titles {
    height			:	22px;
    padding-top		:	5px;
    color			:	#<?php echo $ecomm_font_color; ?>;
    background		:	#<?php echo $ecomm_back_color; ?>;
    border			:	1px solid #<?php echo $ecomm_line_color; ?>;
    border-left		:	0;
    border-right	:	0;
    }

    .buttons_clear {
    height			:	20px;
    }

    .widget_wrapper {
    width			:	100%;
    height			:	28px;
    clear			:	both;
    position		:	relative;
    top				:	-5px;
    }

    #cart_widget {
    float			:	right;
    font-size		:	12px;
    }

    #cart_widget p {
    margin			:	2px 5px 0 0;
    }


    /* E-Commerce Shopping Cart Page
    -------------------------------------------------------------- */

    #shopping_cart_wrapper {
    width			:	100%;
    margin			:	5px auto;
    }

    #shopping_cart_wrapper .buttons {
    width			:	100%;
    text-align		:	right;
    margin			:	0 auto;
    padding-bottom	:	25px;
    }

    #shopping_cart_wrapper .cart_contents {
    width			:	100%;
    clear			:	both;
    margin			:	10px 0;
    }

    #shopping_cart_wrapper .item_wrapper {
    width			:	100%;
    clear			:	both;
    margin			:	5px 0;
    padding			:	5px 0 10px 0;
    border-bottom	:	1px dashed #<?php echo $ecomm_line_color; ?>;
    height			:	auto;
    overflow		: 	auto;
    }

    #shopping_cart_wrapper .cart_contents .cart_image {
    width			:	25%;
    float			:	left;
    }

    #shopping_cart_wrapper .cart_contents .cart_image img {
    max-height		:	<?php echo (150-($ecomm_line_size*2)); ?>px;
    border			:	<?php echo $ecomm_line_size; ?>px solid #<?php echo $ecomm_line_color; ?>;
    }

    #shopping_cart_wrapper .cart_contents .cart_items {
    width			:	75%;
    float			:	left;
    }

    #shopping_cart_wrapper .cart_contents .cart_qty,
    #shopping_cart_wrapper .cart_contents .cart_desc,
    #shopping_cart_wrapper .cart_contents .cart_amt,
    #shopping_cart_wrapper .cart_contents .cart_line {
    height			:	25px;
    font-size		:	13px;
    }

    #shopping_cart_wrapper .cart_contents .cart_qty {
    width			:	8%;
    padding-top		:	0;
    }

    #shopping_cart_wrapper .cart_contents .cart_desc {
    width			:	70%;
    padding-top		:	0;
    }

    #shopping_cart_wrapper .cart_contents .cart_amt {
    width			:	11%;
    padding-top		:	0;
    }

    #shopping_cart_wrapper .cart_contents .cart_line {
    width			:	11%;
    padding-top		:	0;
    font-weight		:	bold;
    text-align		:	right;
    }

    #shopping_cart_wrapper .cart_contents .titles {
    height			:	20px;
    padding-top		:	2px;
    }

    #shopping_cart_wrapper .cart_total_wrapper {
    width			:	260px;
    padding			:	10px;
    float			:	right;
    clear			:	both;
    border			:	1px solid #<?php echo $ecomm_line_color; ?>;
    background		:	#<?php echo $ecomm_back_color; ?>;
    color			:	#<?php echo $ecomm_font_color; ?>;
    }

    #shopping_cart_wrapper .cart_total_wrapper .cart_total {
    width			:	58%;
    font-weight		:	bold;
    float			:	left;
    padding-top		:	3px;
    font-size		:	13px;
    text-align		:	right;
    }

    #shopping_cart_wrapper .cart_total_wrapper .cart_total_amount {
    width			:	42%;
    float			:	left;
    font-size		:	13px;
    font-weight		:	bold;
    text-align		:	right;
    }

    #shopping_cart_wrapper .cart_total_wrapper .cart_total_amount input {
    width			:	60px;
    border			:	0;
    padding			:	0;
    font-size		:	13px;
    text-align		:	right;
    font-weight		:	bold;
    color			:	#<?php echo $ecomm_font_color; ?>;
    background		:	#<?php echo $ecomm_back_color; ?>;
    }

    .checkout_fields {
    display			:	none;
    width			:	100%;
    clear			:	both;
    padding			:	10px 0;
    text-align		:	center;
    }

    .checkout_fields .checkout_wrapper {
    width			:	65%;
    min-height		:	300px;
    clear			:	both;
    margin			:	0 auto;
    padding			:	15px;
    text-align		:	left;
    }

    .checkout_fields .checkout_wrapper .lable {
    width			:	30%;
    float			:	left;
    font-weight		:	bold;
    margin-bottom	:	10px;
    }

    .checkout_fields .checkout_wrapper .field {
    width			:	70%;
    float			:	left;
    text-align		:	right;
    margin-bottom	:	10px;
    }

    .checkout_fields .checkout_wrapper .field input {
    width			:	350px;
    }

    .checkout_fields .checkout_wrapper .field input,
    .checkout_fields .checkout_wrapper .field select {
    padding			:	3px;
    border			:	1px solid #<?php echo $ecomm_line_color; ?>;
    font-size		:	13px;
    }

    .checkout_footer {
    width			:	100%;
    clear			:	both;
    padding			:	0 0 15px 0;
    font-size		:	12px;
    text-align		:	justify;
    }

    .checkout_image {
    width			:	100%;
    clear			:	both;
    padding			:	10px 0 0 0;
    text-align		:	right;
    }


    /* Footer Wrapper
    -------------------------------------------------------------- */

    .footer_wrapper { /* This sets the size and font styles of the footer area */
    clear			: 	both;
<?php if($one_column) { ?>
    width			:	990px;
    margin			:	0 auto;
<?php } else { ?>
    width			: 	100%;
<?php } ?>
    text-align 		: 	center;
    padding			:	5px 0 5px 0;
    background		:	<?php if($footer_background <> 'transparent') { echo '#'; } ?><?php echo $footer_background; ?>;
    margin-top		:	-<?php echo $footer_height; ?>px;
    height			:	<?php echo $footer_height; ?>px;
    clear			:	both;
    z-index			:	2;
    position		:	relative;
    }


    /* Footer Widget Styles
    -------------------------------------------------------------- */

    .footer-widget-area { /* This is the footer widget wrapper */
    display			:	inline-block;
    background		:	none;
    width			:	980px;
    min-height		:	50px;
    color			:	#<?php echo $footer_font_color; ?>;
    font-size		:	<?php echo $footer_font; ?>px;
    font-family     :   <?php echo $fonts->get_css_value($footer_font_style) ?>;
<?php if ($footer_font_weight): ?>
    font-weight     :   <?php echo $footer_font_weight ?>;
<?php endif ?>
<?php if ($footer_font_italic): ?>
    font-style      :   <?php echo $footer_font_italic ?>;
<?php endif ?>
    text-decoration :   <?php echo $footer_font_decoration ?>;
<?php if ($footer_font_case != 'none'): ?>
    text-transform  :   <?php echo $footer_font_case ?>
<?php endif ?>
    margin			:	0 auto;
    }

    .footer-widget-container { /* This is the footer widget container */
    display			:	inline-block;
    background		:	none;
    height			:	auto;
    float			:	left;
    padding			:	10px;
    text-align		:	left;
    margin-bottom	:	5px;
    }

    .footer-widget-container .widget-title { /* This sets the style of the footer widget titles */
    font-size		:	<?php echo $footer_widget_title; ?>px;
    font-family     :   <?php echo $fonts->get_css_value($footer_widget_style) ?>;
    color			:	#<?php echo $footer_widget_color; ?>;
<?php if ($footer_widget_weight): ?>
    font-weight     :   <?php echo $footer_widget_weight ?>;
<?php endif ?>
<?php if ($footer_widget_italic): ?>
    font-style      :   <?php echo $footer_widget_italic ?>;
<?php endif ?>
<?php if ($footer_widget_case != 'none'): ?>
    text-transform  :   <?php echo $footer_widget_case ?>;
<?php endif ?>
    text-decoration :   <?php echo $footer_widget_decoration ?>;
    }

    .footer-widget-container a { /* This sets the color of the footer widget links */
    color			:	#<?php echo $footer_link_color; ?>;
    }

    .footer-widget-container a:hover,
    .footer-widget-container a:active { /* This sets the color and style of the hover and active states of the footer widget links */
    color			:	#<?php echo $footer_link_hover_color; ?>;
    text-decoration	:	<?php echo $footer_link_hover_style; ?>;
    }

    #footer-widgets .footer-widget-container ul {
    margin-left: 0px;
    }

    #footer-widgets .footer-widget-container ul li { /* This styles the footer widget bullet styles */
    list-style-type	: 	none;
    line-height		: 	2;
    padding-left	: 	0px;
    border-bottom	: 	1px dotted #999;
    }

    #footer-widgets .footer-widget-container ul li a:visited { /* This styles the footer widget bullet styles */
    color			: 	#<?php echo $footer_font_color; ?>;
    }


    /* Footer Style
    -------------------------------------------------------------- */

    #footer { /* This sets the size and font styles of the footer area */
    clear			: 	both;
    width			: 	960px;
    text-align 		: 	center;
    margin			:	15px auto 15px auto;
    padding-top 	: 	5px;
    color 			: 	#<?php echo $footer_font_color; ?>;
    font-size		: 	<?php echo $footer_font; ?>px;
    font-family     :   <?php echo $fonts->get_css_value($footer_font_style) ?>;
    }

    #footer a { /* This sets the color of the footer links */
    color			:	#<?php echo $footer_link_color; ?>;
    }

    #footer a:hover,
    #footer a:active { /* This sets the color and style of the hover and active states of the footer links */
    color			:	#<?php echo $footer_link_hover_color; ?>;
    text-decoration	:	<?php echo $footer_link_hover_style; ?>;
    }

    #footer #site-info {
    clear			: 	both;
    margin			:	5px 7px 0 7px;
    font-size		:	14px;
    }

    #footer #site-info p {
    z-index			:	3;
    }


    /* Custom CSS Code
    -------------------------------------------------------------- */

<?php
echo str_replace("\'", "'", str_replace('\"', '"', $custom_css));
?>
